const fs = require('node:fs');
const path = require('node:path');
const {
  findMeteorTestVersionArtifacts,
} = require('./meteorTestVersionArtifacts.cjs');

const versionsPath = path.resolve(__dirname, '../.meteor/versions');
const artifacts = findMeteorTestVersionArtifacts(fs.readFileSync(versionsPath, 'utf8'));

if (artifacts.length > 0) {
  console.error(
    [
      '.meteor/versions contains Meteor test-driver resolutions:',
      ...artifacts.map((line) => `  ${line}`),
      'These entries are generated by meteor test and must not be committed as application dependencies.',
    ].join('\n'),
  );
  process.exit(1);
}

console.log('Meteor application version manifest contains no test-driver artifacts.');
