import type { TargetUiLocale } from './lib/interfaceLocales';
import type { PublicExperienceKey } from './deploymentBrandProfile';

export type { PublicExperienceKey } from './deploymentBrandProfile';

const ENGLISH_PUBLIC_EXPERIENCE = {
  brandTagline: 'Adaptive learning',
  navStudents: 'Students',
  navTeachers: 'Teachers',
  navResearchers: 'Researchers',
  signIn: 'Sign in',
  createAccount: 'Create account',
  eyebrow: 'Built on learning science',
  heroTitle: 'Practice that adapts to the learner.',
  heroCopy: 'MoFaCTS uses each response and the learner’s practice history to decide what comes next.',
  tryMofacts: 'Explore the demos',
  capabilitiesTitle: 'One platform for learning, teaching, and research',
  capabilitiesCopy: 'Create adaptive lessons, manage courses, review learning data, and run controlled studies.',
  demosTitle: 'Choose a role',
  demosCopy: 'No sign-up required. Demo sessions last 24 hours.',
  studentTitle: 'Try adaptive practice',
  studentCopy: 'Practice locating countries on a map while MoFaCTS adjusts what comes next based on your responses.',
  studentAction: 'Start the map demo',
  teacherTitle: 'Explore an AutoTutor lesson',
  teacherCopy: 'Try an AI-guided conversation about natural selection, built around learning goals and common misconceptions.',
  teacherAction: 'Start the AutoTutor demo',
  researcherTitle: 'Explore a 2×2 study',
  researcherCopy: 'See how a study can vary practice scheduling and response format, then experience one of four conditions.',
  researcherAction: 'Start the research demo',
  source: 'Source code',
  project: 'About the project',
  terms: 'Terms of service',
  demoTemporary: 'Interactive demo',
  demoEnglish: 'Demo content is in English.',
  demoPrivacy: 'No sign-up is required. The demo account and its learning data are deleted after 24 hours.',
  demoStart: 'Start demo',
  demoStarting: 'Starting the demo…',
  demoResume: 'Continue demo',
  demoExpired: 'Your previous demo session has expired. Start a new demo.',
  demoFailed: 'We couldn’t start the demo. Please try again.',
  demoExit: 'Back to overview',
  demoSignedIn: 'To start a public demo, sign out of your account first.',
  researchDesign: 'Practice schedule (adaptive or fixed) × response format (typed recall or multiple choice)',
  liveAi: 'This demo uses a live AI service. If the service is unavailable, the demo will let you know.',
} as const;

const DEMO_SESSION_COPY = {
  fr: { demoResume: 'Continuer la démo', demoExpired: 'Votre session de démo précédente a expiré. Démarrez une nouvelle démo.' },
  bn: { demoResume: 'ডেমো চালিয়ে যান', demoExpired: 'আপনার আগের ডেমো সেশনের মেয়াদ শেষ হয়েছে। একটি নতুন ডেমো শুরু করুন।' },
  pt: { demoResume: 'Continuar demonstração', demoExpired: 'Sua sessão de demonstração anterior expirou. Inicie uma nova demonstração.' },
  id: { demoResume: 'Lanjutkan demo', demoExpired: 'Sesi demo Anda sebelumnya telah berakhir. Mulai demo baru.' },
  ur: { demoResume: 'ڈیمو جاری رکھیں', demoExpired: 'آپ کے پچھلے ڈیمو سیشن کی میعاد ختم ہو گئی ہے۔ نیا ڈیمو شروع کریں۔' },
} as const;

export const DEFAULT_PUBLIC_EXPERIENCE_TRANSLATIONS: Record<TargetUiLocale, Record<PublicExperienceKey, string>> = {
  en: ENGLISH_PUBLIC_EXPERIENCE,
  'zh-Hans': {
    brandTagline: '自适应学习', navStudents: '学生', navTeachers: '教师', navResearchers: '研究人员', signIn: '登录', createAccount: '创建账户', eyebrow: '基于学习科学', heroTitle: '随学习者而调整的练习。', heroCopy: 'MoFaCTS 会根据每次作答和学习者的练习历史决定下一步内容。', tryMofacts: '探索演示', capabilitiesTitle: '一个面向学习、教学和研究的平台', capabilitiesCopy: '创建自适应课程、管理课程、查看学习数据并开展受控研究。', demosTitle: '选择角色', demosCopy: '无需注册。演示会话可持续 24 小时。', studentTitle: '体验自适应练习', studentCopy: '在地图上练习定位国家，MoFaCTS 会根据您的作答调整下一步内容。', studentAction: '开始地图演示', teacherTitle: '探索 AutoTutor 课程', teacherCopy: '体验一场由 AI 引导的自然选择对话，内容围绕学习目标和常见误解设计。', teacherAction: '开始 AutoTutor 演示', researcherTitle: '探索 2×2 研究', researcherCopy: '了解研究如何改变练习安排和作答形式，然后体验四个条件之一。', researcherAction: '开始研究演示', source: '源代码', project: '了解项目', terms: '服务条款', demoTemporary: '交互式演示', demoEnglish: '演示内容为英语。', demoPrivacy: '无需注册。演示账户及其学习数据将在 24 小时后删除。', demoStart: '开始演示', demoStarting: '正在启动演示…', demoResume: '继续演示', demoExpired: '您之前的演示会话已过期。请开始新的演示。', demoFailed: '无法启动演示。请重试。', demoExit: '返回概览', demoSignedIn: '要开始公开演示，请先退出您的账户。', researchDesign: '练习安排（自适应或固定）× 作答形式（输入回忆或多项选择）', liveAi: '本演示使用实时 AI 服务。如果该服务不可用，演示会告知您。',
  },
  hi: {
    brandTagline: 'अनुकूली अधिगम', navStudents: 'विद्यार्थी', navTeachers: 'शिक्षक', navResearchers: 'शोधकर्ता', signIn: 'साइन इन', createAccount: 'खाता बनाएँ', eyebrow: 'अधिगम विज्ञान पर आधारित', heroTitle: 'अभ्यास जो शिक्षार्थी के अनुसार ढलता है।', heroCopy: 'MoFaCTS प्रत्येक उत्तर और शिक्षार्थी के अभ्यास इतिहास का उपयोग करके तय करता है कि आगे क्या आएगा।', tryMofacts: 'डेमो देखें', capabilitiesTitle: 'सीखने, सिखाने और शोध के लिए एक मंच', capabilitiesCopy: 'अनुकूली पाठ बनाएँ, पाठ्यक्रम प्रबंधित करें, अधिगम डेटा देखें और नियंत्रित अध्ययन चलाएँ।', demosTitle: 'भूमिका चुनें', demosCopy: 'साइन-अप की आवश्यकता नहीं। डेमो सत्र 24 घंटे चलते हैं।', studentTitle: 'अनुकूली अभ्यास आज़माएँ', studentCopy: 'मानचित्र पर देशों का स्थान पहचानने का अभ्यास करें; MoFaCTS आपके उत्तरों के आधार पर आगे की सामग्री समायोजित करता है।', studentAction: 'मानचित्र डेमो शुरू करें', teacherTitle: 'AutoTutor पाठ देखें', teacherCopy: 'प्राकृतिक चयन पर AI-निर्देशित बातचीत आज़माएँ, जो अधिगम लक्ष्यों और सामान्य भ्रांतियों पर आधारित है।', teacherAction: 'AutoTutor डेमो शुरू करें', researcherTitle: '2×2 अध्ययन देखें', researcherCopy: 'देखें कि अध्ययन अभ्यास क्रम और उत्तर प्रारूप को कैसे बदल सकता है, फिर चार स्थितियों में से एक का अनुभव करें।', researcherAction: 'शोध डेमो शुरू करें', source: 'स्रोत कोड', project: 'परियोजना के बारे में', terms: 'सेवा की शर्तें', demoTemporary: 'इंटरैक्टिव डेमो', demoEnglish: 'डेमो की सामग्री अंग्रेज़ी में है।', demoPrivacy: 'साइन-अप की आवश्यकता नहीं। डेमो खाता और उसका अधिगम डेटा 24 घंटे बाद हटा दिया जाता है।', demoStart: 'डेमो शुरू करें', demoStarting: 'डेमो शुरू हो रहा है…', demoResume: 'डेमो जारी रखें', demoExpired: 'आपका पिछला डेमो सत्र समाप्त हो गया है। नया डेमो शुरू करें।', demoFailed: 'हम डेमो शुरू नहीं कर सके। कृपया फिर कोशिश करें।', demoExit: 'परिचय पर लौटें', demoSignedIn: 'सार्वजनिक डेमो शुरू करने के लिए पहले अपने खाते से साइन आउट करें।', researchDesign: 'अभ्यास क्रम (अनुकूली या निश्चित) × उत्तर प्रारूप (टाइप की गई स्मृति या बहुविकल्प)', liveAi: 'यह डेमो एक लाइव AI सेवा का उपयोग करता है। सेवा उपलब्ध न होने पर डेमो आपको बताएगा।',
  },
  es: {
    brandTagline: 'Aprendizaje adaptativo', navStudents: 'Estudiantes', navTeachers: 'Docentes', navResearchers: 'Investigadores', signIn: 'Iniciar sesión', createAccount: 'Crear cuenta', eyebrow: 'Basado en la ciencia del aprendizaje', heroTitle: 'Práctica que se adapta al estudiante.', heroCopy: 'MoFaCTS usa cada respuesta y el historial de práctica del estudiante para decidir qué sigue.', tryMofacts: 'Explorar las demostraciones', capabilitiesTitle: 'Una plataforma para aprender, enseñar e investigar', capabilitiesCopy: 'Crea lecciones adaptativas, administra cursos, consulta datos de aprendizaje y realiza estudios controlados.', demosTitle: 'Elige un rol', demosCopy: 'No es necesario registrarse. Las sesiones de demostración duran 24 horas.', studentTitle: 'Prueba la práctica adaptativa', studentCopy: 'Practica la ubicación de países en un mapa mientras MoFaCTS ajusta lo que sigue según tus respuestas.', studentAction: 'Iniciar la demostración del mapa', teacherTitle: 'Explora una lección de AutoTutor', teacherCopy: 'Prueba una conversación sobre selección natural guiada por IA y diseñada en torno a objetivos de aprendizaje y errores comunes.', teacherAction: 'Iniciar la demostración de AutoTutor', researcherTitle: 'Explora un estudio 2×2', researcherCopy: 'Observa cómo un estudio puede variar la programación de la práctica y el formato de respuesta, y luego experimenta una de cuatro condiciones.', researcherAction: 'Iniciar la demostración de investigación', source: 'Código fuente', project: 'Acerca del proyecto', terms: 'Términos del servicio', demoTemporary: 'Demostración interactiva', demoEnglish: 'El contenido de la demostración está en inglés.', demoPrivacy: 'No es necesario registrarse. La cuenta de demostración y sus datos de aprendizaje se eliminan después de 24 horas.', demoStart: 'Iniciar demostración', demoStarting: 'Iniciando la demostración…', demoResume: 'Continuar demostración', demoExpired: 'Tu sesión de demostración anterior ha vencido. Inicia una nueva demostración.', demoFailed: 'No pudimos iniciar la demostración. Inténtalo de nuevo.', demoExit: 'Volver al resumen', demoSignedIn: 'Para iniciar una demostración pública, primero cierra la sesión de tu cuenta.', researchDesign: 'Programación de la práctica (adaptativa o fija) × formato de respuesta (recuerdo escrito u opción múltiple)', liveAi: 'Esta demostración usa un servicio de IA en vivo. Si el servicio no está disponible, la demostración te lo indicará.',
  },
  ar: {
    brandTagline: 'تعلم تكيفي', navStudents: 'الطلاب', navTeachers: 'المعلمون', navResearchers: 'الباحثون', signIn: 'تسجيل الدخول', createAccount: 'إنشاء حساب', eyebrow: 'مبني على علم التعلم', heroTitle: 'تدريب يتكيف مع المتعلم.', heroCopy: 'يستخدم MoFaCTS كل إجابة وسجل تدريب المتعلم لتحديد ما يأتي بعد ذلك.', tryMofacts: 'استكشف العروض', capabilitiesTitle: 'منصة واحدة للتعلم والتعليم والبحث', capabilitiesCopy: 'أنشئ دروسًا تكيفية وأدر المقررات وراجع بيانات التعلم ونفّذ دراسات مضبوطة.', demosTitle: 'اختر دورًا', demosCopy: 'لا يلزم التسجيل. تستمر جلسات العرض 24 ساعة.', studentTitle: 'جرّب التدريب التكيفي', studentCopy: 'تدرّب على تحديد مواقع الدول على الخريطة بينما يضبط MoFaCTS ما يأتي لاحقًا استنادًا إلى إجاباتك.', studentAction: 'ابدأ عرض الخريطة', teacherTitle: 'استكشف درس AutoTutor', teacherCopy: 'جرّب محادثة موجّهة بالذكاء الاصطناعي حول الانتقاء الطبيعي، مبنية على أهداف التعلم والمفاهيم الخاطئة الشائعة.', teacherAction: 'ابدأ عرض AutoTutor', researcherTitle: 'استكشف دراسة 2×2', researcherCopy: 'تعرّف إلى كيفية تغيير الدراسة لجدولة التدريب وصيغة الإجابة، ثم جرّب أحد الشروط الأربعة.', researcherAction: 'ابدأ عرض البحث', source: 'الشيفرة المصدرية', project: 'حول المشروع', terms: 'شروط الخدمة', demoTemporary: 'عرض تفاعلي', demoEnglish: 'محتوى العرض باللغة الإنجليزية.', demoPrivacy: 'لا يلزم التسجيل. يُحذف حساب العرض وبيانات التعلم الخاصة به بعد 24 ساعة.', demoStart: 'ابدأ العرض', demoStarting: 'جارٍ بدء العرض…', demoResume: 'تابع العرض', demoExpired: 'انتهت صلاحية جلسة العرض السابقة. ابدأ عرضًا جديدًا.', demoFailed: 'تعذر بدء العرض. حاول مرة أخرى.', demoExit: 'العودة إلى النظرة العامة', demoSignedIn: 'لبدء عرض عام، سجّل الخروج من حسابك أولًا.', researchDesign: 'جدولة التدريب (تكيفية أو ثابتة) × صيغة الإجابة (استدعاء مكتوب أو اختيار من متعدد)', liveAi: 'يستخدم هذا العرض خدمة ذكاء اصطناعي مباشرة. إذا لم تتوفر الخدمة، فسيخبرك العرض بذلك.',
  },
  fr: {
    ...DEMO_SESSION_COPY.fr,
    brandTagline: 'Apprentissage adaptatif', navStudents: 'Étudiants', navTeachers: 'Enseignants', navResearchers: 'Chercheurs', signIn: 'Se connecter', createAccount: 'Créer un compte', eyebrow: 'Fondé sur les sciences de l’apprentissage', heroTitle: 'Une pratique qui s’adapte à l’apprenant.', heroCopy: 'MoFaCTS utilise chaque réponse et l’historique de pratique de l’apprenant pour décider de la suite.', tryMofacts: 'Explorer les démos', capabilitiesTitle: 'Une plateforme pour apprendre, enseigner et faire de la recherche', capabilitiesCopy: 'Créez des leçons adaptatives, gérez des cours, consultez les données d’apprentissage et menez des études contrôlées.', demosTitle: 'Choisissez un rôle', demosCopy: 'Aucune inscription requise. Les sessions de démo durent 24 heures.', studentTitle: 'Essayer la pratique adaptative', studentCopy: 'Entraînez-vous à localiser des pays sur une carte tandis que MoFaCTS adapte la suite à vos réponses.', studentAction: 'Démarrer la démo cartographique', teacherTitle: 'Explorer une leçon AutoTutor', teacherCopy: 'Essayez une conversation sur la sélection naturelle guidée par l’IA et conçue autour d’objectifs d’apprentissage et d’idées fausses courantes.', teacherAction: 'Démarrer la démo AutoTutor', researcherTitle: 'Explorer une étude 2×2', researcherCopy: 'Voyez comment une étude peut faire varier la planification de la pratique et le format de réponse, puis vivez l’une des quatre conditions.', researcherAction: 'Démarrer la démo de recherche', source: 'Code source', project: 'À propos du projet', terms: 'Conditions d’utilisation', demoTemporary: 'Démo interactive', demoEnglish: 'Le contenu de la démo est en anglais.', demoPrivacy: 'Aucune inscription requise. Le compte de démo et ses données d’apprentissage sont supprimés après 24 heures.', demoStart: 'Démarrer la démo', demoStarting: 'Démarrage de la démo…', demoFailed: 'Nous n’avons pas pu démarrer la démo. Réessayez.', demoExit: 'Retour à la présentation', demoSignedIn: 'Pour démarrer une démo publique, déconnectez-vous d’abord de votre compte.', researchDesign: 'Planification de la pratique (adaptative ou fixe) × format de réponse (rappel saisi ou choix multiple)', liveAi: 'Cette démo utilise un service d’IA en direct. Si le service est indisponible, la démo vous en informera.',
  },
  bn: {
    ...DEMO_SESSION_COPY.bn,
    brandTagline: 'অভিযোজিত শেখা', navStudents: 'শিক্ষার্থী', navTeachers: 'শিক্ষক', navResearchers: 'গবেষক', signIn: 'সাইন ইন', createAccount: 'অ্যাকাউন্ট তৈরি', eyebrow: 'শেখার বিজ্ঞানের ভিত্তিতে', heroTitle: 'শিক্ষার্থীর সঙ্গে মানিয়ে নেওয়া অনুশীলন।', heroCopy: 'পরবর্তী কী হবে তা ঠিক করতে MoFaCTS প্রতিটি উত্তর ও শিক্ষার্থীর অনুশীলনের ইতিহাস ব্যবহার করে।', tryMofacts: 'ডেমো দেখুন', capabilitiesTitle: 'শেখা, শেখানো ও গবেষণার জন্য একটি প্ল্যাটফর্ম', capabilitiesCopy: 'অভিযোজিত পাঠ তৈরি করুন, কোর্স পরিচালনা করুন, শেখার ডেটা দেখুন এবং নিয়ন্ত্রিত গবেষণা চালান।', demosTitle: 'একটি ভূমিকা বেছে নিন', demosCopy: 'সাইন-আপের প্রয়োজন নেই। ডেমো সেশন ২৪ ঘণ্টা স্থায়ী হয়।', studentTitle: 'অভিযোজিত অনুশীলন চেষ্টা করুন', studentCopy: 'মানচিত্রে দেশের অবস্থান অনুশীলন করুন; আপনার উত্তরের ভিত্তিতে MoFaCTS পরবর্তী বিষয় ঠিক করে।', studentAction: 'মানচিত্র ডেমো শুরু করুন', teacherTitle: 'একটি AutoTutor পাঠ দেখুন', teacherCopy: 'শেখার লক্ষ্য ও প্রচলিত ভুল ধারণাকে কেন্দ্র করে তৈরি প্রাকৃতিক নির্বাচন বিষয়ে AI-নির্দেশিত কথোপকথন চেষ্টা করুন।', teacherAction: 'AutoTutor ডেমো শুরু করুন', researcherTitle: 'একটি ২×২ গবেষণা দেখুন', researcherCopy: 'একটি গবেষণায় অনুশীলনের সময়সূচি ও উত্তর বিন্যাস কীভাবে বদলানো যায় তা দেখুন, তারপর চারটি শর্তের একটি অনুভব করুন।', researcherAction: 'গবেষণা ডেমো শুরু করুন', source: 'সোর্স কোড', project: 'প্রকল্প সম্পর্কে', terms: 'সেবার শর্ত', demoTemporary: 'ইন্টারঅ্যাক্টিভ ডেমো', demoEnglish: 'ডেমোর বিষয়বস্তু ইংরেজিতে।', demoPrivacy: 'সাইন-আপের প্রয়োজন নেই। ডেমো অ্যাকাউন্ট ও তার শেখার ডেটা ২৪ ঘণ্টা পরে মুছে ফেলা হয়।', demoStart: 'ডেমো শুরু করুন', demoStarting: 'ডেমো শুরু হচ্ছে…', demoFailed: 'আমরা ডেমো শুরু করতে পারিনি। আবার চেষ্টা করুন।', demoExit: 'পরিচিতিতে ফিরুন', demoSignedIn: 'উন্মুক্ত ডেমো শুরু করতে আগে আপনার অ্যাকাউন্ট থেকে সাইন আউট করুন।', researchDesign: 'অনুশীলনের সময়সূচি (অভিযোজিত বা স্থির) × উত্তর বিন্যাস (টাইপ করা স্মরণ বা বহুনির্বাচনী)', liveAi: 'এই ডেমো একটি সরাসরি AI সেবা ব্যবহার করে। সেবাটি না পাওয়া গেলে ডেমো আপনাকে জানাবে।',
  },
  pt: {
    ...DEMO_SESSION_COPY.pt,
    brandTagline: 'Aprendizagem adaptativa', navStudents: 'Estudantes', navTeachers: 'Professores', navResearchers: 'Pesquisadores', signIn: 'Entrar', createAccount: 'Criar conta', eyebrow: 'Baseado na ciência da aprendizagem', heroTitle: 'Prática que se adapta ao estudante.', heroCopy: 'O MoFaCTS usa cada resposta e o histórico de prática do estudante para decidir o que vem a seguir.', tryMofacts: 'Explorar as demonstrações', capabilitiesTitle: 'Uma plataforma para aprender, ensinar e pesquisar', capabilitiesCopy: 'Crie lições adaptativas, gerencie cursos, consulte dados de aprendizagem e realize estudos controlados.', demosTitle: 'Escolha uma função', demosCopy: 'Não é necessário se cadastrar. As sessões de demonstração duram 24 horas.', studentTitle: 'Experimente a prática adaptativa', studentCopy: 'Pratique a localização de países em um mapa enquanto o MoFaCTS ajusta o que vem a seguir com base nas suas respostas.', studentAction: 'Iniciar a demonstração do mapa', teacherTitle: 'Explore uma lição do AutoTutor', teacherCopy: 'Experimente uma conversa sobre seleção natural guiada por IA e criada em torno de objetivos de aprendizagem e equívocos comuns.', teacherAction: 'Iniciar a demonstração do AutoTutor', researcherTitle: 'Explore um estudo 2×2', researcherCopy: 'Veja como um estudo pode variar o agendamento da prática e o formato de resposta e, em seguida, experimente uma das quatro condições.', researcherAction: 'Iniciar a demonstração de pesquisa', source: 'Código-fonte', project: 'Sobre o projeto', terms: 'Termos de serviço', demoTemporary: 'Demonstração interativa', demoEnglish: 'O conteúdo da demonstração está em inglês.', demoPrivacy: 'Não é necessário se cadastrar. A conta de demonstração e seus dados de aprendizagem são excluídos após 24 horas.', demoStart: 'Iniciar demonstração', demoStarting: 'Iniciando a demonstração…', demoFailed: 'Não foi possível iniciar a demonstração. Tente novamente.', demoExit: 'Voltar à visão geral', demoSignedIn: 'Para iniciar uma demonstração pública, primeiro saia da sua conta.', researchDesign: 'Agendamento da prática (adaptativo ou fixo) × formato de resposta (recordação digitada ou múltipla escolha)', liveAi: 'Esta demonstração usa um serviço de IA ao vivo. Se o serviço estiver indisponível, a demonstração informará você.',
  },
  id: {
    ...DEMO_SESSION_COPY.id,
    brandTagline: 'Pembelajaran adaptif', navStudents: 'Siswa', navTeachers: 'Pengajar', navResearchers: 'Peneliti', signIn: 'Masuk', createAccount: 'Buat akun', eyebrow: 'Berdasarkan ilmu pembelajaran', heroTitle: 'Latihan yang menyesuaikan diri dengan pelajar.', heroCopy: 'MoFaCTS menggunakan setiap respons dan riwayat latihan pelajar untuk menentukan apa yang muncul berikutnya.', tryMofacts: 'Jelajahi demo', capabilitiesTitle: 'Satu platform untuk belajar, mengajar, dan meneliti', capabilitiesCopy: 'Buat pelajaran adaptif, kelola kursus, tinjau data pembelajaran, dan jalankan studi terkontrol.', demosTitle: 'Pilih peran', demosCopy: 'Tidak perlu mendaftar. Sesi demo berlangsung selama 24 jam.', studentTitle: 'Coba latihan adaptif', studentCopy: 'Berlatih menemukan negara pada peta sementara MoFaCTS menyesuaikan langkah berikutnya berdasarkan respons Anda.', studentAction: 'Mulai demo peta', teacherTitle: 'Jelajahi pelajaran AutoTutor', teacherCopy: 'Coba percakapan tentang seleksi alam yang dipandu AI dan disusun berdasarkan tujuan pembelajaran serta miskonsepsi umum.', teacherAction: 'Mulai demo AutoTutor', researcherTitle: 'Jelajahi studi 2×2', researcherCopy: 'Lihat bagaimana studi dapat mengubah penjadwalan latihan dan format respons, lalu alami satu dari empat kondisi.', researcherAction: 'Mulai demo penelitian', source: 'Kode sumber', project: 'Tentang proyek', terms: 'Ketentuan layanan', demoTemporary: 'Demo interaktif', demoEnglish: 'Konten demo tersedia dalam bahasa Inggris.', demoPrivacy: 'Tidak perlu mendaftar. Akun demo dan data pembelajarannya dihapus setelah 24 jam.', demoStart: 'Mulai demo', demoStarting: 'Memulai demo…', demoFailed: 'Kami tidak dapat memulai demo. Coba lagi.', demoExit: 'Kembali ke gambaran umum', demoSignedIn: 'Untuk memulai demo publik, keluar dari akun Anda terlebih dahulu.', researchDesign: 'Penjadwalan latihan (adaptif atau tetap) × format respons (ingatan ketik atau pilihan ganda)', liveAi: 'Demo ini menggunakan layanan AI langsung. Jika layanan tidak tersedia, demo akan memberi tahu Anda.',
  },
  ur: {
    ...DEMO_SESSION_COPY.ur,
    brandTagline: 'موافق پذیر تعلیم', navStudents: 'طلبہ', navTeachers: 'اساتذہ', navResearchers: 'محققین', signIn: 'سائن ان', createAccount: 'اکاؤنٹ بنائیں', eyebrow: 'سیکھنے کی سائنس پر مبنی', heroTitle: 'مشق جو سیکھنے والے کے مطابق ڈھلتی ہے۔', heroCopy: 'MoFaCTS ہر جواب اور سیکھنے والے کی مشق کی تاریخ سے طے کرتا ہے کہ آگے کیا آئے گا۔', tryMofacts: 'ڈیمو دیکھیں', capabilitiesTitle: 'سیکھنے، پڑھانے اور تحقیق کے لیے ایک پلیٹ فارم', capabilitiesCopy: 'موافق پذیر اسباق بنائیں، کورسز کا انتظام کریں، سیکھنے کا ڈیٹا دیکھیں اور منضبط مطالعات چلائیں۔', demosTitle: 'ایک کردار منتخب کریں', demosCopy: 'سائن اپ کی ضرورت نہیں۔ ڈیمو سیشن 24 گھنٹے تک رہتے ہیں۔', studentTitle: 'موافق پذیر مشق آزمائیں', studentCopy: 'نقشے پر ملکوں کے مقامات کی مشق کریں جبکہ MoFaCTS آپ کے جوابات کی بنیاد پر اگلا مرحلہ طے کرتا ہے۔', studentAction: 'نقشے کا ڈیمو شروع کریں', teacherTitle: 'AutoTutor سبق دیکھیں', teacherCopy: 'قدرتی انتخاب کے بارے میں AI کی رہنمائی میں گفتگو آزمائیں، جو سیکھنے کے مقاصد اور عام غلط فہمیوں کے گرد بنائی گئی ہے۔', teacherAction: 'AutoTutor ڈیمو شروع کریں', researcherTitle: '2×2 مطالعہ دیکھیں', researcherCopy: 'دیکھیں کہ مطالعہ مشق کے شیڈول اور جواب کی شکل کو کیسے بدل سکتا ہے، پھر چار حالتوں میں سے ایک کا تجربہ کریں۔', researcherAction: 'تحقیقی ڈیمو شروع کریں', source: 'سورس کوڈ', project: 'منصوبے کے بارے میں', terms: 'سروس کی شرائط', demoTemporary: 'انٹرایکٹو ڈیمو', demoEnglish: 'ڈیمو کا مواد انگریزی میں ہے۔', demoPrivacy: 'سائن اپ کی ضرورت نہیں۔ ڈیمو اکاؤنٹ اور اس کا سیکھنے کا ڈیٹا 24 گھنٹے بعد حذف کر دیا جاتا ہے۔', demoStart: 'ڈیمو شروع کریں', demoStarting: 'ڈیمو شروع ہو رہا ہے…', demoFailed: 'ہم ڈیمو شروع نہیں کر سکے۔ دوبارہ کوشش کریں۔', demoExit: 'تعارف پر واپس جائیں', demoSignedIn: 'عوامی ڈیمو شروع کرنے کے لیے پہلے اپنے اکاؤنٹ سے سائن آؤٹ کریں۔', researchDesign: 'مشق کا شیڈول (موافق پذیر یا مقرر) × جواب کی شکل (ٹائپ شدہ یاد یا متعدد انتخاب)', liveAi: 'یہ ڈیمو براہ راست AI سروس استعمال کرتا ہے۔ سروس دستیاب نہ ہو تو ڈیمو آپ کو بتا دے گا۔',
  },
};

export function publicExperienceText(locale: TargetUiLocale, key: PublicExperienceKey): string {
  return DEFAULT_PUBLIC_EXPERIENCE_TRANSLATIONS[locale][key];
}
