FROM geoffreybooth/meteor-base:1.6.1.1

# Copy app package.json and package-lock.json into container
COPY ./mofacts/package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

#COPY ./mofacts/* $APP_SOURCE_FOLDER/

WORKDIR $APP_SOURCE_FOLDER

#CMD cp -r node_modules ./mofacts/ && cp package*.json ./mofacts/ && cd ./mofacts && pwd && ls && meteor --settings ./example.settings.json

EXPOSE 3000
