export {
  H5P_DEFAULT_PREFERRED_HEIGHT,
  H5P_MAX_PREFERRED_HEIGHT,
  H5P_MIN_PREFERRED_HEIGHT,
  clampH5PPreferredHeight,
  getH5PDisplayConfig,
  isExternalH5PConfig,
  isExternalH5PDisplay,
  isSelfHostedH5PConfig,
  isSelfHostedH5PDisplay,
  normalizeH5PDisplayConfig,
  normalizeH5PDisplayConfigPhase1,
  validateH5PDisplayConfig,
  validateH5PDisplayConfigPhase1,
  type H5PValidationResult,
} from '../../../learning-components/trial-displays/h5p/h5pDisplay';
