import type { CreationModuleId } from './aiContentTypes';

export function buildItemAuthoringPrompt(sourceText: string, selectedModules: CreationModuleId[]) {
  return [
    'Return compact normalized import-ready JSON, not raw TDF.',
    'Create a shared item pool usable for the selected MoFaCTS modules.',
    `Selected modules: ${selectedModules.join(', ')}`,
    'If the user specifies what should be stimulus and response, follow that instruction.',
    'If the user asks for a specific number of items, use that number when the source can support it.',
    'If no item count is specified, aim for about 50 flash-card/practice items for learning sessions and about 20 quiz items for assessment sessions. Use fewer when the source has fewer atomic facts, and more only when the source clearly supports more.',
    'Split the material into atomic knowledge components: each item should practice one discrete fact, concept, distinction, procedure step, vocabulary mapping, or application.',
    'Prefer short typed responses for terms, labels, numbers, and short phrases.',
    'Prefer multiple choice when the correct response is long, ambiguous to type, conceptual, or has plausible misconceptions.',
    'For multiple choice, make incorrect responses plausible student errors or common misconceptions, not jokes or arbitrary wrong answers.',
    'Avoid paragraph free-response answers.',
    'The learner-visible cue must not give away the answer. Do not put the correctResponse, the target name, or the answer label inside prompt.text, image captions, hints, definitions, examples, descriptions, or other visible learner text.',
    'When prompt.text is a definition, clue, description, or identification cue, write it so the learner must infer the correctResponse. Do not reuse the answer words in the cue. For example, if the correctResponse is "Yellow Warbler", prompt.text must not say "yellow warbler" or otherwise name that answer.',
    'Treat the source content as the user request plus any pasted material. If the user names a coherent educational topic without details, build from ordinary domain knowledge for that topic rather than treating the missing details as empty source.',
    'When pasted source material is specific, prefer that material and do not add unsupported claims that conflict with it.',
    'Do not duplicate items or create near-duplicate prompts that practice the same atomic knowledge component in the same way.',
    'Do not refuse sparse but coherent educational requests; expand from ordinary domain knowledge when the request is a general topic such as the Krebs cycle, multiplication tables, or common vocabulary.',
    'If the source is abusive, sexual, incoherent, or not an educational topic, return an empty items array and explain the issue in creationSummary.',
    'When the requested learning topic is naturally visual, such as birds, animals, plants, landmarks, artwork, tools, body parts, or diagrams, set promptType to "text-image" or "image" and include prompt.imgSrc for each item when a public, educational image URL is available.',
    'For visual identification images, prefer Wikimedia Commons or Wikipedia lead-image URLs. Use direct HTTPS image URLs that can render in a browser, and include evidence-backed attribution with sourceUrl, licenseName, and licenseUrl.',
    'If you cannot provide an image URL with attribution evidence for a visual identification item, still create the item when educationally useful, but omit imgSrc for that item.',
    'Set visibility to "public" only for general knowledge, original generated wording, public-domain/openly licensed material, or user-provided material that is clearly shareable. Set visibility to "private" when copied source wording, images, audio, or other media may be copyrighted or the license is unclear.',
    'When attribution is warranted for copied or closely adapted licensed/public-domain source material, put attribution on prompt.attribution using creatorName, sourceName, sourceUrl, licenseName, and licenseUrl. Do not add attribution for ordinary general knowledge, arithmetic facts, or dictionary-like facts.',
    'Return JSON only with this shape:',
    JSON.stringify({
      lessonName: 'short lesson title',
      instructions: 'optional learner instructions',
      promptType: 'text',
      responseType: 'typed',
      shuffle: true,
      buttonOrder: 'random',
      textToSpeechMode: 'none',
      topBarMode: 'time-score',
      visibility: 'private',
      tags: ['optional', 'tags'],
      items: [{
        prompt: {
          text: 'learner-visible question, definition, description, or content clue that does not name or give away the correctResponse',
          imgSrc: 'optional direct HTTPS image URL for visual identification items',
          attribution: {
            creatorName: '',
            sourceName: '',
            sourceUrl: '',
            licenseName: '',
            licenseUrl: '',
          },
        },
        response: { correctResponse: 'answer', incorrectResponses: ['distractor 1', 'distractor 2', 'distractor 3'] },
        sourceType: 'freeResponse',
      }],
      creationSummary: 'one or two sentence summary of what was created',
    }, null, 2),
    '',
    'Source content:',
    sourceText,
  ].join('\n');
}

export function buildAutoTutorAuthoringPrompt(sourceText: string) {
  return [
    'Return compact normalized AutoTutor creation JSON, not raw TDF.',
    'Create one MoFaCTS AutoTutor script from the source content.',
    'Treat the source content as the user request plus any pasted material. If the user names a coherent educational topic without details, build from ordinary domain knowledge for that topic rather than treating the missing details as empty source.',
    'When pasted source material is specific, prefer that material and do not add unsupported claims that conflict with it.',
    'If the user asks for a specific number of expectations, use that number when the source can support it. If no count is specified, aim for about 5 expectations.',
    'Expectations should be atomic teachable propositions: each one should represent one discrete knowledge component the learner should articulate.',
    'Misconceptions should be common student misconceptions or likely confusions for this topic, not arbitrary wrong statements.',
    'Keep IDs simple, stable, and unique, such as E1, E2, M1, M2.',
    'Do not duplicate expectations or create near-duplicate misconceptions.',
    'Do not refuse sparse but coherent educational requests; expand from ordinary domain knowledge when the request is a general educational topic such as the Krebs cycle.',
    'If the source is abusive, sexual, incoherent, or not an educational topic, return an empty expectations array and explain the issue in creationSummary.',
    'Set visibility to "public" only for general knowledge, original generated wording, public-domain/openly licensed material, or user-provided material that is clearly shareable. Set visibility to "private" when copied source wording or media may be copyrighted or the license is unclear.',
    'When attribution is warranted for copied or closely adapted licensed/public-domain source material, put it in attribution using creatorName, sourceName, sourceUrl, licenseName, and licenseUrl. Do not add attribution for ordinary general knowledge, arithmetic facts, or dictionary-like facts.',
    'Return JSON only with this shape:',
    JSON.stringify({
      lessonName: 'short title',
      prompt: 'opening question shown to the learner',
      topic: 'topic',
      learningGoal: 'learning goal',
      idealAnswer: 'ideal learner answer',
      expectations: [{
        id: 'E1',
        label: 'short label',
        proposition: 'one key proposition learners should articulate',
        hints: ['brief hint'],
        prompts: [{ stem: 'prompt stem', target: 'target answer part' }],
        assertion: 'clear instructional assertion',
      }],
      misconceptions: [{
        id: 'M1',
        label: 'short label',
        misconception: 'likely mistaken belief',
        detectionCues: ['cue phrase'],
        contrastWithExpectations: ['E1'],
        correction: 'correction',
        repairQuestion: 'repair question',
        repairCriteria: 'how to decide the misconception is repaired',
        acceptableRepairAnswers: ['acceptable repair answer'],
      }],
      maxTurns: 20,
      requiredExpectationCount: 1,
      maxActiveMisconceptions: 0,
      visibility: 'private',
      attribution: {
        creatorName: '',
        sourceName: '',
        sourceUrl: '',
        licenseName: '',
        licenseUrl: '',
      },
      summary: 'short content summary',
      creationSummary: 'one or two sentence creation summary',
    }, null, 2),
    '',
    'Source content:',
    sourceText,
  ].join('\n');
}
