services:
  mongodb:
    entrypoint: !override
      - /usr/local/bin/docker-entrypoint.sh
    command: !override
      - --storageEngine=wiredTiger
      - --auth
    healthcheck: !override
      test: ["CMD-SHELL", "mongosh --quiet --host 127.0.0.1:27017 --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval \"quit(db.adminCommand({ping:1}).ok===1 ? 0 : 1)\""]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 20s
