#!/bin/bash

echo "Removing use of symlinks from shared folder"
sudo umount .meteor/local -f
rm .meteor/local -rf
mkdir -p .meteor/local

sudo umount packages -f
rm packages -rf
mkdir -p packages

mkdir -p "$HOME/.meteor/local"
sudo mount --bind "$HOME/.meteor/local" .meteor/local

mkdir -p "$HOME/.meteor/packages"
sudo mount --bind "$HOME/.meteor/packages" packages

sudo umount ../custom_packages/meteor-accounts-saml-iis-version-2-10-2020/.npm -f
rm ../custom_packages/meteor-accounts-saml-iis-version-2-10-2020/.npm -rf
mkdir "$HOME/.npm"
mkdir ../custom_packages/meteor-accounts-saml-iis-version-2-10-2020/.npm
sudo mount --bind "$HOME/.npm" ../custom_packages/meteor-accounts-saml-iis-version-2-10-2020/.npm

meteor npm install --no-bin-links

export MONGO_URL=mongodb://localhost:27017/MoFaCT
echo "MONGO_URL=$MONGO_URL"

# Figure command line
CL=$*
if [ ${#CL} -lt 1 ]; then
    echo "Running meteor with --settings ./settings.json"
    meteor --settings ./settings.json
else
    echo "Running meteor with your command line (did you remember --settings?)"
    meteor "$@"
fi
