#!/bin/bash

echo "Removing use of symlinks from shared folder"
sudo umount .meteor/local -f
rm .meteor/local -rf
mkdir -p .meteor/local

sudo umount packages -f
rm packages -rf
mkdir -p packages

mkdir -p "$HOME/.meteor/local"
sudo mount --bind "$HOME/.meteor/local" .meteor/local

mkdir -p "$HOME/.meteor/packages"
sudo mount --bind "$HOME/.meteor/packages" packages

meteor npm install

export MONGO_URL=mongodb://localhost:27017/MoFaCT
echo "MONGO_URL=$MONGO_URL"

# Figure command line
CL=$*
if [ ${#CL} -lt 1 ]; then
    echo "Running meteor with --settings ./settings.json"
    # meteor --release 1.4.2.7 --settings ./settings.json
    meteor --settings ./settings.json
else
    echo "Running meteor with your command line (did you remember --settings?)"
    meteor "$@"
fi
