services:
  playwright-mcp:
    environment:
      BASE_URL: https://staging.optimallearning.org

  mongo-mcp:
    networks:
      - mofacts_app

networks:
  mofacts_app:
    external: true
    name: mofacts_mofacts
