services:
  playwright-mcp:
    environment:
      BASE_URL: http://host.docker.internal:3200

  mongo-mcp:
    networks:
      - mofacts_app

networks:
  mofacts_app:
    external: true
    name: deploy_mofacts
