import type { TargetUiLocale } from '../../../../common/lib/interfaceLocales';

export interface LearningAnalyticsMockStrings {
  title: string;
  mockNotice: string;
  lessonLabel: string;
  timePeriod: string;
  period7d: string;
  period30d: string;
  periodAll: string;
  viewChanged: string;
  attempts: string;
  attemptsDefinition: string;
  accuracy: string;
  accuracyDefinition: string;
  uniqueItems: string;
  uniqueItemsDefinition: string;
  practiceDays: string;
  practiceDaysDefinition: string;
  activeMinutes: string;
  activeMinutesDefinition: string;
  recency: string;
  recencyDefinition: string;
  updated: string;
  yesterday: string;
  daysAgo: string;
  latest28Days: string;
  activityIntroduction: string;
  activitySummary: string;
  noPractice: string;
  practiceDayDescription: string;
  activityLevelNone: string;
  activityLevelLow: string;
  activityLevelMedium: string;
  activityLevelHigh: string;
  week: string;
  dateRange: string;
  activityTableCaption: string;
  estimatedLearning: string;
  estimatedIntroduction: string;
  meanProbability: string;
  meanProbabilityDefinition: string;
  atTarget: string;
  atTargetDefinition: string;
  belowTarget: string;
  belowTargetDefinition: string;
  target: string;
  targetExplanation: string;
  estimateTableCaption: string;
  metric: string;
  value: string;
  whyMetricsDiffer: string;
  retrievalModelExplanation: string;
  retrievalExplanation: string;
  autotutorExplanation: string;
}

const STRINGS = {
  en: {
    title: 'My learning', mockNotice: 'Mock data for Jordan Lee — this page is not connected to your learning history.', lessonLabel: 'Lesson or study set', timePeriod: 'Time period', period7d: '7 days', period30d: '30 days', periodAll: 'All time', viewChanged: 'Showing {period} for {lesson}.',
    attempts: 'Attempts', attemptsDefinition: 'Responses submitted during active practice in the selected period.', accuracy: 'Accuracy', accuracyDefinition: 'Correct responses divided by scored attempts. Shown only when correct/incorrect scoring applies.', uniqueItems: 'Unique items practiced', uniqueItemsDefinition: 'Different lesson items encountered. This is a count, not a coverage percentage.', practiceDays: 'Practice days', practiceDaysDefinition: 'Distinct calendar days with active practice in the selected period.', activeMinutes: 'Active practice minutes', activeMinutesDefinition: 'Time spent actively practicing, excluding time merely logged in or left open.', recency: 'Last practiced', recencyDefinition: 'How recently active practice occurred for this lesson.', updated: 'Updated {date}', yesterday: 'Yesterday', daysAgo: '{count} days ago',
    latest28Days: 'Latest 28 days', activityIntroduction: 'Each square represents one calendar day. Pattern and border weight indicate activity as well as color.', activitySummary: '{days} practice days, {attempts} attempts, and {minutes} active minutes in the latest 28 days.', noPractice: '{date}: no practice.', practiceDayDescription: '{date}: {attempts} attempts and {minutes} active minutes.', activityLevelNone: 'No practice', activityLevelLow: 'Light', activityLevelMedium: 'Moderate', activityLevelHigh: 'High', week: 'Week {number}', dateRange: 'Dates', activityTableCaption: 'Numerical summary of the latest 28 days by week',
    estimatedLearning: 'Estimated learning status', estimatedIntroduction: 'This estimate comes from the lesson learning model; it is not a grade.', meanProbability: 'Mean estimated probability', meanProbabilityDefinition: 'Average modeled probability of a correct response across modeled items.', atTarget: 'At target', atTargetDefinition: 'Modeled items at or above the lesson target.', belowTarget: 'Below target', belowTargetDefinition: 'Modeled items below the lesson target and still benefiting from practice.', target: 'Lesson target', targetExplanation: 'The target for this lesson is {target}. The marker shows that target; the filled bar shows the current mean estimate.', estimateTableCaption: 'Numerical summary of estimated learning status', metric: 'Metric', value: 'Value',
    whyMetricsDiffer: 'Why metrics differ by lesson', retrievalModelExplanation: 'This retrieval-practice lesson supports scored accuracy and a learning model, so both measures are available.', retrievalExplanation: 'This lesson supports scored accuracy but does not expose a learning-model progress contract, so no estimated-learning section is shown.', autotutorExplanation: 'AutoTutor uses conversational responses rather than correct/incorrect scoring, so accuracy and estimated-learning measures are not shown.',
  },
  'zh-Hans': {
    title: '我的学习', mockNotice: 'Jordan Lee 的模拟数据——此页面未连接到您的学习记录。', lessonLabel: '课程或学习集', timePeriod: '时间范围', period7d: '7 天', period30d: '30 天', periodAll: '全部时间', viewChanged: '正在显示 {lesson} 的{period}数据。',
    attempts: '尝试次数', attemptsDefinition: '所选时间内主动练习时提交的回答数。', accuracy: '准确率', accuracyDefinition: '正确回答数除以可评分尝试数。仅在适用对错评分时显示。', uniqueItems: '练习过的不同项目', uniqueItemsDefinition: '遇到的不同课程项目数。这是数量，不是覆盖百分比。', practiceDays: '练习天数', practiceDaysDefinition: '所选时间内进行主动练习的不同日历天数。', activeMinutes: '主动练习分钟', activeMinutesDefinition: '实际主动练习的时间，不包括仅登录或页面保持打开的时间。', recency: '上次练习', recencyDefinition: '最近一次主动练习本课程的时间。', updated: '更新于 {date}', yesterday: '昨天', daysAgo: '{count} 天前',
    latest28Days: '最近 28 天', activityIntroduction: '每个方块代表一个日历日；图案和边框粗细与颜色一起表示活动量。', activitySummary: '最近 28 天练习 {days} 天，共 {attempts} 次尝试和 {minutes} 分钟主动练习。', noPractice: '{date}：无练习。', practiceDayDescription: '{date}：{attempts} 次尝试，{minutes} 分钟主动练习。', activityLevelNone: '无练习', activityLevelLow: '少量', activityLevelMedium: '中等', activityLevelHigh: '较多', week: '第 {number} 周', dateRange: '日期', activityTableCaption: '最近 28 天按周数字汇总',
    estimatedLearning: '估计学习状态', estimatedIntroduction: '此估计来自课程学习模型，并非成绩。', meanProbability: '平均估计概率', meanProbabilityDefinition: '所有建模项目正确回答概率的平均值。', atTarget: '达到目标', atTargetDefinition: '达到或超过课程目标的建模项目。', belowTarget: '低于目标', belowTargetDefinition: '低于课程目标、继续练习仍有帮助的建模项目。', target: '课程目标', targetExplanation: '本课程目标为 {target}。标记表示目标，填充条表示当前平均估计值。', estimateTableCaption: '估计学习状态数字汇总', metric: '指标', value: '数值',
    whyMetricsDiffer: '为什么不同课程的指标不同', retrievalModelExplanation: '此检索练习课程支持准确率评分和学习模型，因此两种指标都可用。', retrievalExplanation: '此课程支持准确率评分，但未提供学习模型进度契约，因此不显示估计学习状态。', autotutorExplanation: 'AutoTutor 使用对话式回答而非对错评分，因此不显示准确率和估计学习状态。',
  },
  hi: {
    title: 'मेरी सीख', mockNotice: 'Jordan Lee के लिए नकली डेटा — यह पृष्ठ आपके सीखने के इतिहास से जुड़ा नहीं है।', lessonLabel: 'पाठ या अध्ययन सेट', timePeriod: 'समय अवधि', period7d: '7 दिन', period30d: '30 दिन', periodAll: 'पूरा समय', viewChanged: '{lesson} के लिए {period} दिखाया जा रहा है।',
    attempts: 'प्रयास', attemptsDefinition: 'चुनी अवधि में सक्रिय अभ्यास के दौरान जमा किए गए उत्तर।', accuracy: 'सटीकता', accuracyDefinition: 'सही उत्तरों को स्कोर किए गए प्रयासों से भाग दिया गया है। केवल सही/गलत स्कोर लागू होने पर दिखता है।', uniqueItems: 'अलग अभ्यास आइटम', uniqueItemsDefinition: 'देखे गए अलग-अलग पाठ आइटम। यह संख्या है, कवरेज प्रतिशत नहीं।', practiceDays: 'अभ्यास के दिन', practiceDaysDefinition: 'चुनी अवधि में सक्रिय अभ्यास वाले अलग कैलेंडर दिन।', activeMinutes: 'सक्रिय अभ्यास मिनट', activeMinutesDefinition: 'वास्तव में अभ्यास में बिताया समय; केवल लॉग इन या खुला पृष्ठ शामिल नहीं।', recency: 'अंतिम अभ्यास', recencyDefinition: 'इस पाठ में सक्रिय अभ्यास कितने समय पहले हुआ।', updated: '{date} को अपडेट', yesterday: 'कल', daysAgo: '{count} दिन पहले',
    latest28Days: 'नवीनतम 28 दिन', activityIntroduction: 'हर वर्ग एक कैलेंडर दिन है। रंग के साथ पैटर्न और बॉर्डर गतिविधि दर्शाते हैं।', activitySummary: 'नवीनतम 28 दिनों में {days} अभ्यास दिन, {attempts} प्रयास और {minutes} सक्रिय मिनट।', noPractice: '{date}: कोई अभ्यास नहीं।', practiceDayDescription: '{date}: {attempts} प्रयास और {minutes} सक्रिय मिनट।', activityLevelNone: 'कोई अभ्यास नहीं', activityLevelLow: 'हल्का', activityLevelMedium: 'मध्यम', activityLevelHigh: 'अधिक', week: 'सप्ताह {number}', dateRange: 'तिथियाँ', activityTableCaption: 'नवीनतम 28 दिनों का साप्ताहिक संख्यात्मक सारांश',
    estimatedLearning: 'अनुमानित सीखने की स्थिति', estimatedIntroduction: 'यह अनुमान पाठ के सीखने के मॉडल से आता है; यह ग्रेड नहीं है।', meanProbability: 'औसत अनुमानित संभावना', meanProbabilityDefinition: 'मॉडल किए गए आइटमों में सही उत्तर की औसत संभावना।', atTarget: 'लक्ष्य पर', atTargetDefinition: 'पाठ लक्ष्य पर या उससे ऊपर के मॉडल किए गए आइटम।', belowTarget: 'लक्ष्य से नीचे', belowTargetDefinition: 'लक्ष्य से नीचे के आइटम जिन्हें और अभ्यास से लाभ होगा।', target: 'पाठ लक्ष्य', targetExplanation: 'इस पाठ का लक्ष्य {target} है। चिह्न लक्ष्य और भरी पट्टी वर्तमान औसत अनुमान दिखाती है।', estimateTableCaption: 'अनुमानित सीखने की स्थिति का संख्यात्मक सारांश', metric: 'माप', value: 'मान',
    whyMetricsDiffer: 'पाठों में माप अलग क्यों हैं', retrievalModelExplanation: 'यह पुनर्प्राप्ति-अभ्यास पाठ स्कोर की गई सटीकता और सीखने के मॉडल दोनों का समर्थन करता है।', retrievalExplanation: 'यह पाठ सटीकता का समर्थन करता है, लेकिन सीखने-मॉडल प्रगति अनुबंध नहीं देता, इसलिए अनुमानित स्थिति नहीं दिखाई जाती।', autotutorExplanation: 'AutoTutor सही/गलत स्कोर के बजाय संवादात्मक उत्तर उपयोग करता है, इसलिए सटीकता और अनुमानित स्थिति नहीं दिखाई जाती।',
  },
  es: {
    title: 'Mi aprendizaje', mockNotice: 'Datos simulados de Jordan Lee; esta página no está conectada a tu historial de aprendizaje.', lessonLabel: 'Lección o conjunto de estudio', timePeriod: 'Período', period7d: '7 días', period30d: '30 días', periodAll: 'Todo el tiempo', viewChanged: 'Mostrando {period} de {lesson}.',
    attempts: 'Intentos', attemptsDefinition: 'Respuestas enviadas durante la práctica activa en el período seleccionado.', accuracy: 'Precisión', accuracyDefinition: 'Respuestas correctas divididas por intentos puntuados. Solo aparece cuando corresponde puntuar correcto/incorrecto.', uniqueItems: 'Elementos únicos practicados', uniqueItemsDefinition: 'Elementos diferentes encontrados. Es un recuento, no un porcentaje de cobertura.', practiceDays: 'Días de práctica', practiceDaysDefinition: 'Días calendario distintos con práctica activa en el período seleccionado.', activeMinutes: 'Minutos de práctica activa', activeMinutesDefinition: 'Tiempo de práctica activa, sin contar estar conectado o dejar la página abierta.', recency: 'Última práctica', recencyDefinition: 'Cuándo ocurrió la práctica activa más reciente de esta lección.', updated: 'Actualizado {date}', yesterday: 'Ayer', daysAgo: 'Hace {count} días',
    latest28Days: 'Últimos 28 días', activityIntroduction: 'Cada cuadro representa un día. El patrón y el borde indican actividad además del color.', activitySummary: '{days} días de práctica, {attempts} intentos y {minutes} minutos activos en los últimos 28 días.', noPractice: '{date}: sin práctica.', practiceDayDescription: '{date}: {attempts} intentos y {minutes} minutos activos.', activityLevelNone: 'Sin práctica', activityLevelLow: 'Ligera', activityLevelMedium: 'Moderada', activityLevelHigh: 'Alta', week: 'Semana {number}', dateRange: 'Fechas', activityTableCaption: 'Resumen numérico semanal de los últimos 28 días',
    estimatedLearning: 'Estado de aprendizaje estimado', estimatedIntroduction: 'Esta estimación proviene del modelo de aprendizaje de la lección; no es una calificación.', meanProbability: 'Probabilidad media estimada', meanProbabilityDefinition: 'Probabilidad media modelada de responder correctamente los elementos modelados.', atTarget: 'En el objetivo', atTargetDefinition: 'Elementos modelados que alcanzan o superan el objetivo.', belowTarget: 'Bajo el objetivo', belowTargetDefinition: 'Elementos bajo el objetivo que aún se benefician de la práctica.', target: 'Objetivo de la lección', targetExplanation: 'El objetivo de esta lección es {target}. La marca muestra el objetivo y la barra la estimación media actual.', estimateTableCaption: 'Resumen numérico del aprendizaje estimado', metric: 'Métrica', value: 'Valor',
    whyMetricsDiffer: 'Por qué las métricas cambian entre lecciones', retrievalModelExplanation: 'Esta lección de recuperación admite precisión puntuada y un modelo de aprendizaje; ambas medidas están disponibles.', retrievalExplanation: 'Esta lección admite precisión, pero no expone progreso de un modelo de aprendizaje; por eso se omite esa sección.', autotutorExplanation: 'AutoTutor usa respuestas conversacionales, no puntuación correcto/incorrecto; por eso no muestra precisión ni aprendizaje estimado.',
  },
  ar: {
    title: 'تعلّمي', mockNotice: 'بيانات تجريبية للطالب Jordan Lee — هذه الصفحة غير متصلة بسجل تعلمك.', lessonLabel: 'الدرس أو مجموعة الدراسة', timePeriod: 'الفترة الزمنية', period7d: '7 أيام', period30d: '30 يومًا', periodAll: 'كل الوقت', viewChanged: 'عرض {period} للدرس {lesson}.',
    attempts: 'المحاولات', attemptsDefinition: 'الإجابات المقدمة أثناء التدريب النشط في الفترة المحددة.', accuracy: 'الدقة', accuracyDefinition: 'الإجابات الصحيحة مقسومة على المحاولات المقيمة. تظهر فقط عند تطبيق تقييم صحيح/خطأ.', uniqueItems: 'العناصر الفريدة المتدرّب عليها', uniqueItemsDefinition: 'عدد عناصر الدرس المختلفة التي تمت ممارستها، وليس نسبة تغطية.', practiceDays: 'أيام التدريب', practiceDaysDefinition: 'أيام التقويم المختلفة التي تضمنت تدريبًا نشطًا في الفترة المحددة.', activeMinutes: 'دقائق التدريب النشط', activeMinutesDefinition: 'وقت التدريب الفعلي دون وقت تسجيل الدخول فقط أو ترك الصفحة مفتوحة.', recency: 'آخر تدريب', recencyDefinition: 'مدى حداثة آخر تدريب نشط على هذا الدرس.', updated: 'تم التحديث {date}', yesterday: 'أمس', daysAgo: 'منذ {count} أيام',
    latest28Days: 'آخر 28 يومًا', activityIntroduction: 'يمثل كل مربع يومًا. يوضح النمط وسُمك الحد النشاط إلى جانب اللون.', activitySummary: '{days} أيام تدريب و{attempts} محاولة و{minutes} دقيقة نشطة خلال آخر 28 يومًا.', noPractice: '{date}: لا يوجد تدريب.', practiceDayDescription: '{date}: {attempts} محاولة و{minutes} دقيقة نشطة.', activityLevelNone: 'لا تدريب', activityLevelLow: 'خفيف', activityLevelMedium: 'متوسط', activityLevelHigh: 'مرتفع', week: 'الأسبوع {number}', dateRange: 'التواريخ', activityTableCaption: 'ملخص رقمي أسبوعي لآخر 28 يومًا',
    estimatedLearning: 'حالة التعلم المقدّرة', estimatedIntroduction: 'يأتي هذا التقدير من نموذج تعلم الدرس، وليس درجة.', meanProbability: 'متوسط الاحتمال المقدّر', meanProbabilityDefinition: 'متوسط الاحتمال النموذجي للإجابة الصحيحة عبر العناصر المنمذجة.', atTarget: 'عند الهدف', atTargetDefinition: 'العناصر المنمذجة عند هدف الدرس أو أعلى منه.', belowTarget: 'دون الهدف', belowTargetDefinition: 'العناصر دون الهدف التي لا تزال تستفيد من التدريب.', target: 'هدف الدرس', targetExplanation: 'هدف هذا الدرس هو {target}. تشير العلامة إلى الهدف ويبين الشريط المتوسط الحالي.', estimateTableCaption: 'ملخص رقمي لحالة التعلم المقدّرة', metric: 'المقياس', value: 'القيمة',
    whyMetricsDiffer: 'لماذا تختلف المقاييس بين الدروس', retrievalModelExplanation: 'يدعم هذا الدرس دقة مقيمة ونموذج تعلم، لذا يتوفر كلا المقياسين.', retrievalExplanation: 'يدعم هذا الدرس الدقة لكنه لا يوفر عقد تقدم لنموذج تعلم، لذلك لا يظهر قسم التعلم المقدّر.', autotutorExplanation: 'يستخدم AutoTutor إجابات حوارية بدل تقييم صحيح/خطأ، لذلك لا تظهر الدقة أو حالة التعلم المقدّرة.',
  },
  fr: {
    title: 'Mon apprentissage', mockNotice: 'Données fictives pour Jordan Lee — cette page n’est pas reliée à votre historique d’apprentissage.', lessonLabel: 'Leçon ou ensemble d’étude', timePeriod: 'Période', period7d: '7 jours', period30d: '30 jours', periodAll: 'Depuis le début', viewChanged: 'Affichage de {period} pour {lesson}.',
    attempts: 'Tentatives', attemptsDefinition: 'Réponses soumises pendant la pratique active au cours de la période choisie.', accuracy: 'Exactitude', accuracyDefinition: 'Réponses correctes divisées par les tentatives notées. Affichée uniquement si la notation correct/incorrect s’applique.', uniqueItems: 'Éléments distincts pratiqués', uniqueItemsDefinition: 'Nombre d’éléments différents rencontrés, et non un pourcentage de couverture.', practiceDays: 'Jours de pratique', practiceDaysDefinition: 'Jours calendaires distincts avec pratique active pendant la période choisie.', activeMinutes: 'Minutes de pratique active', activeMinutesDefinition: 'Temps de pratique active, hors simple connexion ou page laissée ouverte.', recency: 'Dernière pratique', recencyDefinition: 'Date de la pratique active la plus récente pour cette leçon.', updated: 'Mis à jour {date}', yesterday: 'Hier', daysAgo: 'Il y a {count} jours',
    latest28Days: '28 derniers jours', activityIntroduction: 'Chaque case représente un jour. Le motif et la bordure indiquent aussi l’activité, en plus de la couleur.', activitySummary: '{days} jours de pratique, {attempts} tentatives et {minutes} minutes actives sur les 28 derniers jours.', noPractice: '{date} : aucune pratique.', practiceDayDescription: '{date} : {attempts} tentatives et {minutes} minutes actives.', activityLevelNone: 'Aucune', activityLevelLow: 'Faible', activityLevelMedium: 'Modérée', activityLevelHigh: 'Élevée', week: 'Semaine {number}', dateRange: 'Dates', activityTableCaption: 'Résumé numérique hebdomadaire des 28 derniers jours',
    estimatedLearning: 'État d’apprentissage estimé', estimatedIntroduction: 'Cette estimation provient du modèle d’apprentissage de la leçon ; ce n’est pas une note.', meanProbability: 'Probabilité moyenne estimée', meanProbabilityDefinition: 'Probabilité moyenne modélisée d’une réponse correcte sur les éléments modélisés.', atTarget: 'À l’objectif', atTargetDefinition: 'Éléments modélisés ayant atteint ou dépassé l’objectif.', belowTarget: 'Sous l’objectif', belowTargetDefinition: 'Éléments sous l’objectif qui bénéficient encore de la pratique.', target: 'Objectif de la leçon', targetExplanation: 'L’objectif de cette leçon est {target}. Le repère indique l’objectif et la barre l’estimation moyenne actuelle.', estimateTableCaption: 'Résumé numérique de l’apprentissage estimé', metric: 'Mesure', value: 'Valeur',
    whyMetricsDiffer: 'Pourquoi les mesures varient selon la leçon', retrievalModelExplanation: 'Cette leçon prend en charge l’exactitude notée et un modèle d’apprentissage ; les deux mesures sont disponibles.', retrievalExplanation: 'Cette leçon prend en charge l’exactitude mais pas de contrat de progression du modèle ; la section estimée est donc absente.', autotutorExplanation: 'AutoTutor utilise des réponses conversationnelles plutôt qu’une notation correct/incorrect ; l’exactitude et l’estimation ne sont donc pas affichées.',
  },
  bn: {
    title: 'আমার শেখা', mockNotice: 'Jordan Lee-এর নমুনা তথ্য — এই পৃষ্ঠাটি আপনার শেখার ইতিহাসের সঙ্গে যুক্ত নয়।', lessonLabel: 'পাঠ বা স্টাডি সেট', timePeriod: 'সময়কাল', period7d: '৭ দিন', period30d: '৩০ দিন', periodAll: 'সর্বকাল', viewChanged: '{lesson}-এর {period} দেখানো হচ্ছে।',
    attempts: 'চেষ্টা', attemptsDefinition: 'নির্বাচিত সময়ে সক্রিয় অনুশীলনের সময় জমা দেওয়া উত্তর।', accuracy: 'নির্ভুলতা', accuracyDefinition: 'স্কোর করা চেষ্টার মধ্যে সঠিক উত্তরের হার। সঠিক/ভুল স্কোর প্রযোজ্য হলেই দেখানো হয়।', uniqueItems: 'অনুশীলিত স্বতন্ত্র আইটেম', uniqueItemsDefinition: 'ভিন্ন যে পাঠ আইটেমগুলো দেখা হয়েছে তার সংখ্যা; এটি কভারেজ শতাংশ নয়।', practiceDays: 'অনুশীলনের দিন', practiceDaysDefinition: 'নির্বাচিত সময়ে সক্রিয় অনুশীলনসহ স্বতন্ত্র ক্যালেন্ডার দিন।', activeMinutes: 'সক্রিয় অনুশীলন মিনিট', activeMinutesDefinition: 'শুধু লগইন বা পৃষ্ঠা খোলা রাখার সময় বাদ দিয়ে সক্রিয় অনুশীলনের সময়।', recency: 'শেষ অনুশীলন', recencyDefinition: 'এই পাঠে কত সম্প্রতি সক্রিয় অনুশীলন হয়েছে।', updated: 'আপডেট {date}', yesterday: 'গতকাল', daysAgo: '{count} দিন আগে',
    latest28Days: 'সর্বশেষ ২৮ দিন', activityIntroduction: 'প্রতিটি ঘর একটি দিন। রঙের পাশাপাশি নকশা ও সীমানা কার্যকলাপ বোঝায়।', activitySummary: 'সর্বশেষ ২৮ দিনে {days} অনুশীলনের দিন, {attempts} চেষ্টা এবং {minutes} সক্রিয় মিনিট।', noPractice: '{date}: কোনো অনুশীলন নেই।', practiceDayDescription: '{date}: {attempts} চেষ্টা এবং {minutes} সক্রিয় মিনিট।', activityLevelNone: 'অনুশীলন নেই', activityLevelLow: 'হালকা', activityLevelMedium: 'মাঝারি', activityLevelHigh: 'বেশি', week: 'সপ্তাহ {number}', dateRange: 'তারিখ', activityTableCaption: 'সর্বশেষ ২৮ দিনের সাপ্তাহিক সংখ্যাগত সারাংশ',
    estimatedLearning: 'আনুমানিক শেখার অবস্থা', estimatedIntroduction: 'এই অনুমান পাঠের শেখার মডেল থেকে আসে; এটি গ্রেড নয়।', meanProbability: 'গড় আনুমানিক সম্ভাবনা', meanProbabilityDefinition: 'মডেল করা আইটেমে সঠিক উত্তরের গড় সম্ভাবনা।', atTarget: 'লক্ষ্যে', atTargetDefinition: 'পাঠের লক্ষ্যে বা তার ওপরে থাকা মডেল করা আইটেম।', belowTarget: 'লক্ষ্যের নিচে', belowTargetDefinition: 'লক্ষ্যের নিচে থাকা এবং আরও অনুশীলনে উপকৃত হবে এমন আইটেম।', target: 'পাঠের লক্ষ্য', targetExplanation: 'এই পাঠের লক্ষ্য {target}। চিহ্নটি লক্ষ্য এবং পূর্ণ বারটি বর্তমান গড় অনুমান দেখায়।', estimateTableCaption: 'আনুমানিক শেখার অবস্থার সংখ্যাগত সারাংশ', metric: 'পরিমাপ', value: 'মান',
    whyMetricsDiffer: 'পাঠভেদে পরিমাপ আলাদা কেন', retrievalModelExplanation: 'এই রিট্রিভাল অনুশীলন পাঠ স্কোর করা নির্ভুলতা ও শেখার মডেল উভয়ই সমর্থন করে।', retrievalExplanation: 'এই পাঠ নির্ভুলতা সমর্থন করে, কিন্তু শেখার মডেল অগ্রগতি দেয় না; তাই আনুমানিক অংশ দেখানো হয় না।', autotutorExplanation: 'AutoTutor সঠিক/ভুল স্কোরের বদলে কথোপকথনমূলক উত্তর ব্যবহার করে; তাই নির্ভুলতা ও আনুমানিক অবস্থা দেখানো হয় না।',
  },
  pt: {
    title: 'Meu aprendizado', mockNotice: 'Dados simulados de Jordan Lee — esta página não está conectada ao seu histórico de aprendizagem.', lessonLabel: 'Lição ou conjunto de estudo', timePeriod: 'Período', period7d: '7 dias', period30d: '30 dias', periodAll: 'Todo o período', viewChanged: 'Mostrando {period} de {lesson}.',
    attempts: 'Tentativas', attemptsDefinition: 'Respostas enviadas durante a prática ativa no período selecionado.', accuracy: 'Precisão', accuracyDefinition: 'Respostas corretas divididas pelas tentativas pontuadas. Só aparece quando a pontuação certo/errado se aplica.', uniqueItems: 'Itens únicos praticados', uniqueItemsDefinition: 'Itens diferentes encontrados. É uma contagem, não uma porcentagem de cobertura.', practiceDays: 'Dias de prática', practiceDaysDefinition: 'Dias de calendário distintos com prática ativa no período selecionado.', activeMinutes: 'Minutos de prática ativa', activeMinutesDefinition: 'Tempo de prática ativa, sem contar apenas estar conectado ou deixar a página aberta.', recency: 'Última prática', recencyDefinition: 'Quando ocorreu a prática ativa mais recente desta lição.', updated: 'Atualizado em {date}', yesterday: 'Ontem', daysAgo: 'Há {count} dias',
    latest28Days: 'Últimos 28 dias', activityIntroduction: 'Cada quadrado representa um dia. Padrão e borda também indicam atividade, além da cor.', activitySummary: '{days} dias de prática, {attempts} tentativas e {minutes} minutos ativos nos últimos 28 dias.', noPractice: '{date}: sem prática.', practiceDayDescription: '{date}: {attempts} tentativas e {minutes} minutos ativos.', activityLevelNone: 'Sem prática', activityLevelLow: 'Leve', activityLevelMedium: 'Moderada', activityLevelHigh: 'Alta', week: 'Semana {number}', dateRange: 'Datas', activityTableCaption: 'Resumo numérico semanal dos últimos 28 dias',
    estimatedLearning: 'Estado de aprendizagem estimado', estimatedIntroduction: 'Esta estimativa vem do modelo de aprendizagem da lição; não é uma nota.', meanProbability: 'Probabilidade média estimada', meanProbabilityDefinition: 'Probabilidade média modelada de resposta correta nos itens modelados.', atTarget: 'Na meta', atTargetDefinition: 'Itens modelados na meta da lição ou acima dela.', belowTarget: 'Abaixo da meta', belowTargetDefinition: 'Itens abaixo da meta que ainda se beneficiam da prática.', target: 'Meta da lição', targetExplanation: 'A meta desta lição é {target}. O marcador mostra a meta e a barra mostra a estimativa média atual.', estimateTableCaption: 'Resumo numérico da aprendizagem estimada', metric: 'Métrica', value: 'Valor',
    whyMetricsDiffer: 'Por que as métricas variam por lição', retrievalModelExplanation: 'Esta lição de recuperação oferece precisão pontuada e modelo de aprendizagem; as duas medidas estão disponíveis.', retrievalExplanation: 'Esta lição oferece precisão, mas não expõe progresso de modelo; por isso a seção estimada não aparece.', autotutorExplanation: 'O AutoTutor usa respostas conversacionais, não pontuação certo/errado; por isso precisão e aprendizagem estimada não aparecem.',
  },
  id: {
    title: 'Pembelajaran saya', mockNotice: 'Data contoh untuk Jordan Lee — halaman ini tidak terhubung ke riwayat belajar Anda.', lessonLabel: 'Pelajaran atau set belajar', timePeriod: 'Periode waktu', period7d: '7 hari', period30d: '30 hari', periodAll: 'Sepanjang waktu', viewChanged: 'Menampilkan {period} untuk {lesson}.',
    attempts: 'Percobaan', attemptsDefinition: 'Jawaban yang dikirim selama latihan aktif pada periode yang dipilih.', accuracy: 'Akurasi', accuracyDefinition: 'Jawaban benar dibagi percobaan yang dinilai. Hanya tampil jika penilaian benar/salah berlaku.', uniqueItems: 'Item unik yang dilatih', uniqueItemsDefinition: 'Jumlah item pelajaran berbeda yang ditemui, bukan persentase cakupan.', practiceDays: 'Hari latihan', practiceDaysDefinition: 'Hari kalender berbeda dengan latihan aktif pada periode yang dipilih.', activeMinutes: 'Menit latihan aktif', activeMinutesDefinition: 'Waktu latihan aktif, tidak termasuk hanya masuk atau membiarkan halaman terbuka.', recency: 'Terakhir berlatih', recencyDefinition: 'Seberapa baru latihan aktif terjadi untuk pelajaran ini.', updated: 'Diperbarui {date}', yesterday: 'Kemarin', daysAgo: '{count} hari lalu',
    latest28Days: '28 hari terakhir', activityIntroduction: 'Setiap kotak mewakili satu hari. Pola dan ketebalan garis menunjukkan aktivitas selain warna.', activitySummary: '{days} hari latihan, {attempts} percobaan, dan {minutes} menit aktif dalam 28 hari terakhir.', noPractice: '{date}: tidak ada latihan.', practiceDayDescription: '{date}: {attempts} percobaan dan {minutes} menit aktif.', activityLevelNone: 'Tidak ada', activityLevelLow: 'Ringan', activityLevelMedium: 'Sedang', activityLevelHigh: 'Tinggi', week: 'Minggu {number}', dateRange: 'Tanggal', activityTableCaption: 'Ringkasan angka mingguan untuk 28 hari terakhir',
    estimatedLearning: 'Status belajar perkiraan', estimatedIntroduction: 'Perkiraan ini berasal dari model belajar pelajaran; ini bukan nilai.', meanProbability: 'Rata-rata probabilitas perkiraan', meanProbabilityDefinition: 'Rata-rata probabilitas jawaban benar pada item yang dimodelkan.', atTarget: 'Mencapai target', atTargetDefinition: 'Item yang dimodelkan pada atau di atas target pelajaran.', belowTarget: 'Di bawah target', belowTargetDefinition: 'Item di bawah target yang masih mendapat manfaat dari latihan.', target: 'Target pelajaran', targetExplanation: 'Target pelajaran ini {target}. Penanda menunjukkan target dan bilah menunjukkan perkiraan rata-rata saat ini.', estimateTableCaption: 'Ringkasan angka status belajar perkiraan', metric: 'Metrik', value: 'Nilai',
    whyMetricsDiffer: 'Mengapa metrik berbeda antar pelajaran', retrievalModelExplanation: 'Pelajaran latihan pengambilan ini mendukung akurasi yang dinilai dan model belajar, jadi keduanya tersedia.', retrievalExplanation: 'Pelajaran ini mendukung akurasi tetapi tidak menyediakan progres model belajar, jadi bagian perkiraan tidak ditampilkan.', autotutorExplanation: 'AutoTutor memakai jawaban percakapan, bukan penilaian benar/salah, jadi akurasi dan status perkiraan tidak ditampilkan.',
  },
  ur: {
    title: 'میری سیکھنے کی پیش رفت', mockNotice: 'Jordan Lee کے لیے فرضی ڈیٹا — یہ صفحہ آپ کی سیکھنے کی تاریخ سے منسلک نہیں ہے۔', lessonLabel: 'سبق یا مطالعاتی مجموعہ', timePeriod: 'مدت', period7d: '7 دن', period30d: '30 دن', periodAll: 'تمام وقت', viewChanged: '{lesson} کے لیے {period} دکھایا جا رہا ہے۔',
    attempts: 'کوششیں', attemptsDefinition: 'منتخب مدت میں فعال مشق کے دوران جمع کرائے گئے جوابات۔', accuracy: 'درستگی', accuracyDefinition: 'درست جوابات کو اسکور شدہ کوششوں سے تقسیم کیا گیا ہے۔ صرف صحیح/غلط اسکور لاگو ہونے پر دکھائی جاتی ہے۔', uniqueItems: 'منفرد مشق شدہ آئٹمز', uniqueItemsDefinition: 'مختلف سبق آئٹمز کی تعداد؛ یہ کوریج فیصد نہیں ہے۔', practiceDays: 'مشق کے دن', practiceDaysDefinition: 'منتخب مدت میں فعال مشق والے الگ کیلنڈر دن۔', activeMinutes: 'فعال مشق کے منٹ', activeMinutesDefinition: 'حقیقی فعال مشق کا وقت؛ صرف لاگ اِن یا کھلا صفحہ شامل نہیں۔', recency: 'آخری مشق', recencyDefinition: 'اس سبق کی حالیہ فعال مشق کب ہوئی۔', updated: 'اپ ڈیٹ {date}', yesterday: 'کل', daysAgo: '{count} دن پہلے',
    latest28Days: 'حالیہ 28 دن', activityIntroduction: 'ہر خانہ ایک دن ہے۔ رنگ کے ساتھ نمونہ اور بارڈر سرگرمی دکھاتے ہیں۔', activitySummary: 'حالیہ 28 دن میں {days} مشق کے دن، {attempts} کوششیں اور {minutes} فعال منٹ۔', noPractice: '{date}: کوئی مشق نہیں۔', practiceDayDescription: '{date}: {attempts} کوششیں اور {minutes} فعال منٹ۔', activityLevelNone: 'کوئی مشق نہیں', activityLevelLow: 'ہلکی', activityLevelMedium: 'درمیانی', activityLevelHigh: 'زیادہ', week: 'ہفتہ {number}', dateRange: 'تاریخیں', activityTableCaption: 'حالیہ 28 دن کا ہفتہ وار عددی خلاصہ',
    estimatedLearning: 'سیکھنے کی تخمینی حالت', estimatedIntroduction: 'یہ تخمینہ سبق کے سیکھنے کے ماڈل سے ہے؛ یہ گریڈ نہیں ہے۔', meanProbability: 'اوسط تخمینی امکان', meanProbabilityDefinition: 'ماڈل شدہ آئٹمز میں درست جواب کا اوسط امکان۔', atTarget: 'ہدف پر', atTargetDefinition: 'سبق کے ہدف پر یا اس سے اوپر ماڈل شدہ آئٹمز۔', belowTarget: 'ہدف سے نیچے', belowTargetDefinition: 'ہدف سے نیچے آئٹمز جنہیں مزید مشق سے فائدہ ہوگا۔', target: 'سبق کا ہدف', targetExplanation: 'اس سبق کا ہدف {target} ہے۔ نشان ہدف اور بھری پٹی موجودہ اوسط تخمینہ دکھاتی ہے۔', estimateTableCaption: 'سیکھنے کی تخمینی حالت کا عددی خلاصہ', metric: 'پیمانہ', value: 'قدر',
    whyMetricsDiffer: 'اسباق میں پیمانے مختلف کیوں ہیں', retrievalModelExplanation: 'یہ بازیافت مشق سبق اسکور شدہ درستگی اور سیکھنے کے ماڈل دونوں کو سپورٹ کرتا ہے۔', retrievalExplanation: 'یہ سبق درستگی کو سپورٹ کرتا ہے مگر سیکھنے کے ماڈل کی پیش رفت فراہم نہیں کرتا، اس لیے تخمینی حصہ نہیں دکھتا۔', autotutorExplanation: 'AutoTutor صحیح/غلط اسکور کے بجائے گفتگوئی جوابات استعمال کرتا ہے، اس لیے درستگی اور تخمینی حالت نہیں دکھائی جاتی۔',
  },
} satisfies Record<TargetUiLocale, LearningAnalyticsMockStrings>;

export function getLearningAnalyticsMockStrings(locale: TargetUiLocale): LearningAnalyticsMockStrings {
  return STRINGS[locale];
}

export function interpolateLearningAnalyticsMockString(
  template: string,
  values: Record<string, string | number>,
): string {
  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (match, key: string) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}
