import type { TargetUiLocale } from '../../../common/lib/interfaceLocales';

export type PublicExperienceKey = keyof typeof ENGLISH_PUBLIC_EXPERIENCE;

const ENGLISH_PUBLIC_EXPERIENCE = {
  brandTagline: 'Adaptive learning',
  navStudents: 'Students',
  navTeachers: 'Teachers',
  navResearchers: 'Researchers',
  signIn: 'Sign in',
  createAccount: 'Create account',
  eyebrow: 'Adaptive practice, grounded in learning science',
  heroTitle: 'Practice smarter. Remember longer.',
  heroCopy: 'MoFaCTS uses responses and practice history to help select what to study next.',
  tryMofacts: 'Try MoFaCTS',
  capabilitiesTitle: 'One platform, different purposes',
  capabilitiesCopy: 'Practice adaptively, create learning content, organize courses, inspect learning analytics, and deliver controlled studies.',
  demosTitle: 'Choose the view that matches your work',
  demosCopy: 'Each demonstration creates a temporary anonymous session that expires after 24 hours. Lesson content is in English.',
  studentTitle: 'Learn as a student',
  studentCopy: 'Practice country locations while adaptive scheduling responds to what you remember.',
  studentAction: 'Try the map lesson',
  teacherTitle: 'Teach with AutoTutor',
  teacherCopy: 'See a live Natural Selection dialogue grounded in authored expectations and misconceptions.',
  teacherAction: 'Try AutoTutor',
  researcherTitle: 'Run a learning study',
  researcherCopy: 'Inspect a 2×2 design, receive a balanced random assignment, and experience one condition.',
  researcherAction: 'Explore the study',
  source: 'Source code',
  project: 'Project overview',
  terms: 'Terms of service',
  demoTemporary: 'Temporary public demonstration',
  demoEnglish: 'The lesson content is in English.',
  demoPrivacy: 'No email, password, or profile information is requested. The temporary account and learner data expire after 24 hours.',
  demoStart: 'Start demonstration',
  demoStarting: 'Starting your anonymous session…',
  demoResume: 'Resume demonstration',
  demoExpired: 'This temporary demonstration has expired. Start a new anonymous session.',
  demoFailed: 'The demonstration could not be started.',
  demoExit: 'Return to overview',
  demoSignedIn: 'Public demonstrations cannot replace your signed-in account.',
  researchDesign: 'Scheduling (adaptive or fixed) × response format (typed recall or multiple choice)',
  liveAi: 'This demonstration uses the live configured AI service and stops clearly if it is unavailable.',
} as const;

const DEMO_SESSION_COPY = {
  fr: { demoResume: 'Reprendre la démonstration', demoExpired: 'Cette démonstration temporaire a expiré. Démarrez une nouvelle session anonyme.' },
  bn: { demoResume: 'প্রদর্শনী আবার চালু করুন', demoExpired: 'এই অস্থায়ী প্রদর্শনীর মেয়াদ শেষ। নতুন বেনামী সেশন শুরু করুন।' },
  pt: { demoResume: 'Retomar demonstração', demoExpired: 'Esta demonstração temporária expirou. Inicie uma nova sessão anônima.' },
  id: { demoResume: 'Lanjutkan demonstrasi', demoExpired: 'Demonstrasi sementara ini telah berakhir. Mulai sesi anonim baru.' },
  ur: { demoResume: 'مظاہرہ دوبارہ شروع کریں', demoExpired: 'یہ عارضی مظاہرہ ختم ہو چکا ہے۔ نیا گمنام سیشن شروع کریں۔' },
} as const;

const TRANSLATIONS: Record<TargetUiLocale, Record<PublicExperienceKey, string>> = {
  en: ENGLISH_PUBLIC_EXPERIENCE,
  'zh-Hans': {
    brandTagline: '自适应学习', navStudents: '学生', navTeachers: '教师', navResearchers: '研究人员', signIn: '登录', createAccount: '创建账户', eyebrow: '以学习科学为基础的自适应练习', heroTitle: '更聪明地练习，记得更久。', heroCopy: 'MoFaCTS 使用作答和练习历史来帮助选择下一步学习内容。', tryMofacts: '试用 MoFaCTS', capabilitiesTitle: '一个平台，多种用途', capabilitiesCopy: '进行自适应练习、创建学习内容、组织课程、查看学习分析并开展受控研究。', demosTitle: '选择适合您工作的视角', demosCopy: '每个演示都会创建一个临时匿名会话，并在 24 小时后到期。课程内容为英语。', studentTitle: '以学生身份学习', studentCopy: '练习国家位置，自适应安排会根据您的记忆情况作出调整。', studentAction: '试用地图课程', teacherTitle: '使用 AutoTutor 教学', teacherCopy: '查看基于已编写预期和误解的实时自然选择对话。', teacherAction: '试用 AutoTutor', researcherTitle: '运行学习研究', researcherCopy: '查看 2×2 设计，接受平衡随机分配并体验一个条件。', researcherAction: '探索研究', source: '源代码', project: '项目概览', terms: '服务条款', demoTemporary: '临时公开演示', demoEnglish: '课程内容为英语。', demoPrivacy: '无需电子邮件、密码或个人资料。临时账户和学习数据将在 24 小时后到期。', demoStart: '开始演示', demoStarting: '正在启动匿名会话…', demoResume: '继续演示', demoExpired: '此临时演示已过期。请开始新的匿名会话。', demoFailed: '无法启动演示。', demoExit: '返回概览', demoSignedIn: '公开演示不能替换您已登录的账户。', researchDesign: '安排（自适应或固定）× 作答形式（输入回忆或多项选择）', liveAi: '此演示使用实时配置的 AI 服务；若服务不可用，将明确停止。',
  },
  hi: {
    brandTagline: 'अनुकूली अधिगम', navStudents: 'विद्यार्थी', navTeachers: 'शिक्षक', navResearchers: 'शोधकर्ता', signIn: 'साइन इन', createAccount: 'खाता बनाएँ', eyebrow: 'अधिगम विज्ञान पर आधारित अनुकूली अभ्यास', heroTitle: 'बेहतर अभ्यास करें। अधिक समय तक याद रखें।', heroCopy: 'MoFaCTS प्रतिक्रियाओं और अभ्यास इतिहास से अगली अध्ययन सामग्री चुनने में सहायता करता है।', tryMofacts: 'MoFaCTS आज़माएँ', capabilitiesTitle: 'एक मंच, अनेक उद्देश्य', capabilitiesCopy: 'अनुकूली अभ्यास, सामग्री निर्माण, पाठ्यक्रम संगठन, अधिगम विश्लेषण और नियंत्रित अध्ययन।', demosTitle: 'अपने काम के अनुरूप दृश्य चुनें', demosCopy: 'हर प्रदर्शन एक अस्थायी अनाम सत्र बनाता है जो 24 घंटे बाद समाप्त होता है। पाठ अंग्रेज़ी में है।', studentTitle: 'विद्यार्थी की तरह सीखें', studentCopy: 'देशों के स्थानों का अभ्यास करें और अनुकूली क्रम को अपनी स्मृति के अनुसार बदलते देखें।', studentAction: 'मानचित्र पाठ आज़माएँ', teacherTitle: 'AutoTutor से पढ़ाएँ', teacherCopy: 'लेखित अपेक्षाओं और भ्रांतियों पर आधारित लाइव प्राकृतिक चयन संवाद देखें।', teacherAction: 'AutoTutor आज़माएँ', researcherTitle: 'अधिगम अध्ययन चलाएँ', researcherCopy: '2×2 डिज़ाइन देखें, संतुलित यादृच्छिक आवंटन पाएँ और एक स्थिति अनुभव करें।', researcherAction: 'अध्ययन देखें', source: 'स्रोत कोड', project: 'परियोजना परिचय', terms: 'सेवा की शर्तें', demoTemporary: 'अस्थायी सार्वजनिक प्रदर्शन', demoEnglish: 'पाठ की सामग्री अंग्रेज़ी में है।', demoPrivacy: 'ईमेल, पासवर्ड या प्रोफ़ाइल जानकारी नहीं माँगी जाती। अस्थायी खाता और अधिगम डेटा 24 घंटे बाद समाप्त हो जाते हैं।', demoStart: 'प्रदर्शन शुरू करें', demoStarting: 'आपका अनाम सत्र शुरू हो रहा है…', demoResume: 'प्रदर्शन फिर शुरू करें', demoExpired: 'यह अस्थायी प्रदर्शन समाप्त हो गया है। नया अनाम सत्र शुरू करें।', demoFailed: 'प्रदर्शन शुरू नहीं हो सका।', demoExit: 'परिचय पर लौटें', demoSignedIn: 'सार्वजनिक प्रदर्शन आपके साइन-इन खाते को बदल नहीं सकता।', researchDesign: 'क्रम (अनुकूली या निश्चित) × प्रतिक्रिया प्रारूप (टाइप की गई स्मृति या बहुविकल्प)', liveAi: 'यह प्रदर्शन लाइव कॉन्फ़िगर की गई AI सेवा का उपयोग करता है और अनुपलब्ध होने पर स्पष्ट रूप से रुकता है।',
  },
  es: {
    brandTagline: 'Aprendizaje adaptativo', navStudents: 'Estudiantes', navTeachers: 'Docentes', navResearchers: 'Investigadores', signIn: 'Iniciar sesión', createAccount: 'Crear cuenta', eyebrow: 'Práctica adaptativa basada en la ciencia del aprendizaje', heroTitle: 'Practica mejor. Recuerda por más tiempo.', heroCopy: 'MoFaCTS usa las respuestas y el historial de práctica para ayudar a seleccionar qué estudiar después.', tryMofacts: 'Probar MoFaCTS', capabilitiesTitle: 'Una plataforma, distintos propósitos', capabilitiesCopy: 'Practica de forma adaptativa, crea contenido, organiza cursos, consulta análisis y realiza estudios controlados.', demosTitle: 'Elige la perspectiva que corresponda a tu trabajo', demosCopy: 'Cada demostración crea una sesión anónima temporal que vence después de 24 horas. El contenido está en inglés.', studentTitle: 'Aprende como estudiante', studentCopy: 'Practica ubicaciones de países mientras la programación adaptativa responde a lo que recuerdas.', studentAction: 'Probar la lección de mapas', teacherTitle: 'Enseña con AutoTutor', teacherCopy: 'Observa un diálogo en vivo sobre selección natural basado en expectativas y conceptos erróneos definidos.', teacherAction: 'Probar AutoTutor', researcherTitle: 'Realiza un estudio de aprendizaje', researcherCopy: 'Examina un diseño 2×2, recibe una asignación aleatoria equilibrada y experimenta una condición.', researcherAction: 'Explorar el estudio', source: 'Código fuente', project: 'Descripción del proyecto', terms: 'Términos del servicio', demoTemporary: 'Demostración pública temporal', demoEnglish: 'El contenido de la lección está en inglés.', demoPrivacy: 'No se solicita correo, contraseña ni perfil. La cuenta temporal y los datos vencen después de 24 horas.', demoStart: 'Iniciar demostración', demoStarting: 'Iniciando tu sesión anónima…', demoResume: 'Reanudar demostración', demoExpired: 'Esta demostración temporal ha vencido. Inicia una nueva sesión anónima.', demoFailed: 'No se pudo iniciar la demostración.', demoExit: 'Volver al resumen', demoSignedIn: 'Las demostraciones públicas no pueden reemplazar tu cuenta activa.', researchDesign: 'Programación (adaptativa o fija) × formato de respuesta (recuerdo escrito u opción múltiple)', liveAi: 'Esta demostración usa el servicio de IA configurado en vivo y se detiene claramente si no está disponible.',
  },
  ar: {
    brandTagline: 'تعلم تكيفي', navStudents: 'الطلاب', navTeachers: 'المعلمون', navResearchers: 'الباحثون', signIn: 'تسجيل الدخول', createAccount: 'إنشاء حساب', eyebrow: 'تدريب تكيفي قائم على علم التعلم', heroTitle: 'تدرّب بذكاء. وتذكّر لمدة أطول.', heroCopy: 'يستخدم MoFaCTS الإجابات وسجل التدريب للمساعدة في اختيار ما ينبغي دراسته لاحقًا.', tryMofacts: 'جرّب MoFaCTS', capabilitiesTitle: 'منصة واحدة لأغراض متعددة', capabilitiesCopy: 'تدرّب تكيفيًا وأنشئ المحتوى ونظّم المقررات وافحص تحليلات التعلم ونفّذ دراسات مضبوطة.', demosTitle: 'اختر العرض المناسب لعملك', demosCopy: 'ينشئ كل عرض جلسة مجهولة مؤقتة تنتهي بعد 24 ساعة. محتوى الدرس باللغة الإنجليزية.', studentTitle: 'تعلّم كطالب', studentCopy: 'تدرّب على مواقع الدول بينما يستجيب الجدول التكيفي لما تتذكره.', studentAction: 'جرّب درس الخرائط', teacherTitle: 'درّس باستخدام AutoTutor', teacherCopy: 'شاهد حوارًا مباشرًا حول الانتقاء الطبيعي يستند إلى توقعات ومفاهيم خاطئة مؤلفة.', teacherAction: 'جرّب AutoTutor', researcherTitle: 'نفّذ دراسة تعلم', researcherCopy: 'افحص تصميم 2×2 واحصل على تعيين عشوائي متوازن وجرّب شرطًا واحدًا.', researcherAction: 'استكشف الدراسة', source: 'الشيفرة المصدرية', project: 'نظرة عامة على المشروع', terms: 'شروط الخدمة', demoTemporary: 'عرض عام مؤقت', demoEnglish: 'محتوى الدرس باللغة الإنجليزية.', demoPrivacy: 'لا يُطلب بريد إلكتروني أو كلمة مرور أو معلومات ملف شخصي. ينتهي الحساب المؤقت وبيانات التعلم بعد 24 ساعة.', demoStart: 'بدء العرض', demoStarting: 'جارٍ بدء جلستك المجهولة…', demoResume: 'متابعة العرض', demoExpired: 'انتهت صلاحية هذا العرض المؤقت. ابدأ جلسة مجهولة جديدة.', demoFailed: 'تعذر بدء العرض.', demoExit: 'العودة إلى النظرة العامة', demoSignedIn: 'لا يمكن للعروض العامة استبدال حسابك المسجل.', researchDesign: 'الجدولة (تكيفية أو ثابتة) × صيغة الإجابة (استدعاء مكتوب أو اختيار متعدد)', liveAi: 'يستخدم هذا العرض خدمة الذكاء الاصطناعي الحية المهيأة ويتوقف بوضوح إذا لم تتوفر.',
  },
  fr: {
    ...DEMO_SESSION_COPY.fr,
    brandTagline: 'Apprentissage adaptatif', navStudents: 'Étudiants', navTeachers: 'Enseignants', navResearchers: 'Chercheurs', signIn: 'Se connecter', createAccount: 'Créer un compte', eyebrow: 'Pratique adaptative fondée sur les sciences de l’apprentissage', heroTitle: 'Entraînez-vous mieux. Retenez plus longtemps.', heroCopy: 'MoFaCTS utilise les réponses et l’historique de pratique pour aider à choisir quoi étudier ensuite.', tryMofacts: 'Essayer MoFaCTS', capabilitiesTitle: 'Une plateforme, plusieurs usages', capabilitiesCopy: 'Pratique adaptative, création de contenu, cours, analyses d’apprentissage et études contrôlées.', demosTitle: 'Choisissez la perspective adaptée à votre travail', demosCopy: 'Chaque démonstration crée une session anonyme temporaire qui expire après 24 heures. Le contenu est en anglais.', studentTitle: 'Apprendre comme étudiant', studentCopy: 'Entraînez-vous à localiser des pays tandis que la planification adaptative réagit à vos souvenirs.', studentAction: 'Essayer la leçon de cartes', teacherTitle: 'Enseigner avec AutoTutor', teacherCopy: 'Observez un dialogue en direct sur la sélection naturelle fondé sur des attentes et idées fausses rédigées.', teacherAction: 'Essayer AutoTutor', researcherTitle: 'Mener une étude d’apprentissage', researcherCopy: 'Examinez un plan 2×2, recevez une affectation aléatoire équilibrée et vivez une condition.', researcherAction: 'Explorer l’étude', source: 'Code source', project: 'Présentation du projet', terms: 'Conditions d’utilisation', demoTemporary: 'Démonstration publique temporaire', demoEnglish: 'Le contenu de la leçon est en anglais.', demoPrivacy: 'Aucun courriel, mot de passe ou profil n’est demandé. Le compte et les données expirent après 24 heures.', demoStart: 'Démarrer la démonstration', demoStarting: 'Démarrage de votre session anonyme…', demoFailed: 'Impossible de démarrer la démonstration.', demoExit: 'Retour à la présentation', demoSignedIn: 'Une démonstration publique ne peut pas remplacer votre compte connecté.', researchDesign: 'Planification (adaptative ou fixe) × format de réponse (rappel saisi ou choix multiple)', liveAi: 'Cette démonstration utilise le service d’IA configuré en direct et s’arrête clairement s’il est indisponible.',
  },
  bn: {
    ...DEMO_SESSION_COPY.bn,
    brandTagline: 'অভিযোজিত শেখা', navStudents: 'শিক্ষার্থী', navTeachers: 'শিক্ষক', navResearchers: 'গবেষক', signIn: 'সাইন ইন', createAccount: 'অ্যাকাউন্ট তৈরি', eyebrow: 'শেখার বিজ্ঞানের ভিত্তিতে অভিযোজিত অনুশীলন', heroTitle: 'আরও বুদ্ধিমত্তার সঙ্গে অনুশীলন করুন। দীর্ঘদিন মনে রাখুন।', heroCopy: 'পরবর্তী কী পড়তে হবে তা বেছে নিতে MoFaCTS উত্তর ও অনুশীলনের ইতিহাস ব্যবহার করে।', tryMofacts: 'MoFaCTS চেষ্টা করুন', capabilitiesTitle: 'একটি প্ল্যাটফর্ম, বিভিন্ন উদ্দেশ্য', capabilitiesCopy: 'অভিযোজিত অনুশীলন, কনটেন্ট তৈরি, কোর্স সংগঠন, বিশ্লেষণ ও নিয়ন্ত্রিত গবেষণা।', demosTitle: 'আপনার কাজের উপযোগী দৃশ্য বেছে নিন', demosCopy: 'প্রতিটি প্রদর্শনী একটি অস্থায়ী বেনামী সেশন তৈরি করে যা ২৪ ঘণ্টা পরে শেষ হয়। পাঠ ইংরেজিতে।', studentTitle: 'শিক্ষার্থী হিসেবে শিখুন', studentCopy: 'দেশের অবস্থান অনুশীলন করুন এবং অভিযোজিত সময়সূচিকে আপনার স্মৃতির ভিত্তিতে বদলাতে দেখুন।', studentAction: 'মানচিত্র পাঠ চেষ্টা করুন', teacherTitle: 'AutoTutor দিয়ে শেখান', teacherCopy: 'লিখিত প্রত্যাশা ও ভুল ধারণাভিত্তিক প্রাকৃতিক নির্বাচন সংলাপ দেখুন।', teacherAction: 'AutoTutor চেষ্টা করুন', researcherTitle: 'শেখার গবেষণা চালান', researcherCopy: '২×২ নকশা দেখুন, ভারসাম্যপূর্ণ দৈব বরাদ্দ পান এবং একটি শর্ত অনুভব করুন।', researcherAction: 'গবেষণা দেখুন', source: 'সোর্স কোড', project: 'প্রকল্প পরিচিতি', terms: 'সেবার শর্ত', demoTemporary: 'অস্থায়ী উন্মুক্ত প্রদর্শনী', demoEnglish: 'পাঠের বিষয়বস্তু ইংরেজিতে।', demoPrivacy: 'ইমেইল, পাসওয়ার্ড বা প্রোফাইল তথ্য চাওয়া হয় না। অস্থায়ী অ্যাকাউন্ট ও শেখার ডেটা ২৪ ঘণ্টা পরে শেষ হয়।', demoStart: 'প্রদর্শনী শুরু করুন', demoStarting: 'বেনামী সেশন শুরু হচ্ছে…', demoFailed: 'প্রদর্শনী শুরু করা যায়নি।', demoExit: 'পরিচিতিতে ফিরুন', demoSignedIn: 'উন্মুক্ত প্রদর্শনী আপনার সাইন-ইন অ্যাকাউন্ট বদলাতে পারে না।', researchDesign: 'সময়সূচি (অভিযোজিত বা স্থির) × উত্তর বিন্যাস (টাইপ করা স্মরণ বা বহুনির্বাচনী)', liveAi: 'এই প্রদর্শনী সরাসরি কনফিগার করা AI সেবা ব্যবহার করে এবং অনুপলব্ধ হলে স্পষ্টভাবে থামে।',
  },
  pt: {
    ...DEMO_SESSION_COPY.pt,
    brandTagline: 'Aprendizagem adaptativa', navStudents: 'Estudantes', navTeachers: 'Professores', navResearchers: 'Pesquisadores', signIn: 'Entrar', createAccount: 'Criar conta', eyebrow: 'Prática adaptativa baseada na ciência da aprendizagem', heroTitle: 'Pratique melhor. Lembre por mais tempo.', heroCopy: 'O MoFaCTS usa respostas e histórico de prática para ajudar a selecionar o que estudar em seguida.', tryMofacts: 'Experimentar o MoFaCTS', capabilitiesTitle: 'Uma plataforma, diferentes finalidades', capabilitiesCopy: 'Pratique de forma adaptativa, crie conteúdo, organize cursos, consulte análises e realize estudos controlados.', demosTitle: 'Escolha a perspectiva adequada ao seu trabalho', demosCopy: 'Cada demonstração cria uma sessão anônima temporária que expira após 24 horas. O conteúdo está em inglês.', studentTitle: 'Aprenda como estudante', studentCopy: 'Pratique localizações de países enquanto o agendamento adaptativo responde ao que você lembra.', studentAction: 'Experimentar a lição de mapas', teacherTitle: 'Ensine com AutoTutor', teacherCopy: 'Veja um diálogo ao vivo sobre seleção natural baseado em expectativas e equívocos definidos.', teacherAction: 'Experimentar o AutoTutor', researcherTitle: 'Realize um estudo de aprendizagem', researcherCopy: 'Examine um desenho 2×2, receba uma atribuição aleatória equilibrada e vivencie uma condição.', researcherAction: 'Explorar o estudo', source: 'Código-fonte', project: 'Visão geral do projeto', terms: 'Termos de serviço', demoTemporary: 'Demonstração pública temporária', demoEnglish: 'O conteúdo da lição está em inglês.', demoPrivacy: 'Nenhum e-mail, senha ou perfil é solicitado. A conta temporária e os dados expiram após 24 horas.', demoStart: 'Iniciar demonstração', demoStarting: 'Iniciando sua sessão anônima…', demoFailed: 'Não foi possível iniciar a demonstração.', demoExit: 'Voltar à visão geral', demoSignedIn: 'Demonstrações públicas não podem substituir sua conta conectada.', researchDesign: 'Agendamento (adaptativo ou fixo) × formato de resposta (recordação digitada ou múltipla escolha)', liveAi: 'Esta demonstração usa o serviço de IA configurado ao vivo e para claramente se ele estiver indisponível.',
  },
  id: {
    ...DEMO_SESSION_COPY.id,
    brandTagline: 'Pembelajaran adaptif', navStudents: 'Siswa', navTeachers: 'Pengajar', navResearchers: 'Peneliti', signIn: 'Masuk', createAccount: 'Buat akun', eyebrow: 'Latihan adaptif berdasarkan ilmu pembelajaran', heroTitle: 'Berlatih lebih cerdas. Ingat lebih lama.', heroCopy: 'MoFaCTS menggunakan respons dan riwayat latihan untuk membantu memilih materi berikutnya.', tryMofacts: 'Coba MoFaCTS', capabilitiesTitle: 'Satu platform, beragam tujuan', capabilitiesCopy: 'Berlatih adaptif, buat konten, kelola kursus, periksa analitik, dan jalankan studi terkontrol.', demosTitle: 'Pilih tampilan yang sesuai dengan pekerjaan Anda', demosCopy: 'Setiap demonstrasi membuat sesi anonim sementara yang berakhir setelah 24 jam. Isi pelajaran berbahasa Inggris.', studentTitle: 'Belajar sebagai siswa', studentCopy: 'Latih lokasi negara sementara penjadwalan adaptif merespons apa yang Anda ingat.', studentAction: 'Coba pelajaran peta', teacherTitle: 'Mengajar dengan AutoTutor', teacherCopy: 'Lihat dialog langsung Seleksi Alam berdasarkan ekspektasi dan miskonsepsi yang ditulis.', teacherAction: 'Coba AutoTutor', researcherTitle: 'Jalankan studi pembelajaran', researcherCopy: 'Periksa desain 2×2, terima penugasan acak seimbang, dan alami satu kondisi.', researcherAction: 'Jelajahi studi', source: 'Kode sumber', project: 'Gambaran proyek', terms: 'Ketentuan layanan', demoTemporary: 'Demonstrasi publik sementara', demoEnglish: 'Isi pelajaran berbahasa Inggris.', demoPrivacy: 'Tidak ada email, kata sandi, atau profil yang diminta. Akun sementara dan data belajar berakhir setelah 24 jam.', demoStart: 'Mulai demonstrasi', demoStarting: 'Memulai sesi anonim Anda…', demoFailed: 'Demonstrasi tidak dapat dimulai.', demoExit: 'Kembali ke gambaran umum', demoSignedIn: 'Demonstrasi publik tidak dapat menggantikan akun Anda yang sedang masuk.', researchDesign: 'Penjadwalan (adaptif atau tetap) × format respons (ingatan ketik atau pilihan ganda)', liveAi: 'Demonstrasi ini memakai layanan AI terkonfigurasi secara langsung dan berhenti dengan jelas jika tidak tersedia.',
  },
  ur: {
    ...DEMO_SESSION_COPY.ur,
    brandTagline: 'موافق پذیر تعلیم', navStudents: 'طلبہ', navTeachers: 'اساتذہ', navResearchers: 'محققین', signIn: 'سائن ان', createAccount: 'اکاؤنٹ بنائیں', eyebrow: 'سیکھنے کی سائنس پر مبنی موافق پذیر مشق', heroTitle: 'بہتر مشق کریں۔ زیادہ دیر یاد رکھیں۔', heroCopy: 'MoFaCTS جوابات اور مشق کی تاریخ سے اگلا مطالعہ منتخب کرنے میں مدد لیتا ہے۔', tryMofacts: 'MoFaCTS آزمائیں', capabilitiesTitle: 'ایک پلیٹ فارم، مختلف مقاصد', capabilitiesCopy: 'موافق پذیر مشق، مواد کی تخلیق، کورس کی تنظیم، تجزیات اور منضبط مطالعات۔', demosTitle: 'اپنے کام کے مطابق منظر منتخب کریں', demosCopy: 'ہر مظاہرہ ایک عارضی گمنام سیشن بناتا ہے جو 24 گھنٹے بعد ختم ہوتا ہے۔ سبق انگریزی میں ہے۔', studentTitle: 'طالب علم کی طرح سیکھیں', studentCopy: 'ملکوں کے مقامات کی مشق کریں اور نظام کو اپنی یادداشت کے مطابق بدلتے دیکھیں۔', studentAction: 'نقشے کا سبق آزمائیں', teacherTitle: 'AutoTutor سے پڑھائیں', teacherCopy: 'تحریر شدہ توقعات اور غلط فہمیوں پر مبنی قدرتی انتخاب کا براہ راست مکالمہ دیکھیں۔', teacherAction: 'AutoTutor آزمائیں', researcherTitle: 'سیکھنے کا مطالعہ چلائیں', researcherCopy: '2×2 ڈیزائن دیکھیں، متوازن بے ترتیب تخصیص حاصل کریں اور ایک حالت آزمائیں۔', researcherAction: 'مطالعہ دیکھیں', source: 'سورس کوڈ', project: 'منصوبے کا تعارف', terms: 'سروس کی شرائط', demoTemporary: 'عارضی عوامی مظاہرہ', demoEnglish: 'سبق کا مواد انگریزی میں ہے۔', demoPrivacy: 'ای میل، پاس ورڈ یا پروفائل معلومات نہیں مانگی جاتیں۔ عارضی اکاؤنٹ اور ڈیٹا 24 گھنٹے بعد ختم ہو جاتے ہیں۔', demoStart: 'مظاہرہ شروع کریں', demoStarting: 'آپ کا گمنام سیشن شروع ہو رہا ہے…', demoFailed: 'مظاہرہ شروع نہیں ہو سکا۔', demoExit: 'تعارف پر واپس جائیں', demoSignedIn: 'عوامی مظاہرہ آپ کے سائن ان اکاؤنٹ کو تبدیل نہیں کر سکتا۔', researchDesign: 'شیڈولنگ (موافق پذیر یا مقرر) × جواب کی شکل (ٹائپ شدہ یاد یا متعدد انتخاب)', liveAi: 'یہ مظاہرہ براہ راست ترتیب دی گئی AI سروس استعمال کرتا ہے اور عدم دستیابی پر واضح طور پر رک جاتا ہے۔',
  },
};

export function publicExperienceText(locale: TargetUiLocale, key: PublicExperienceKey): string {
  return TRANSLATIONS[locale][key];
}
